// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const addAppointmentServicesBulk = `-- name: AddAppointmentServicesBulk :exec
INSERT INTO appointment_services (tenant_id, appointment_id, service_id)
SELECT $1::uuid, $2::uuid, sid
FROM unnest($3::uuid[]) AS sid
ON CONFLICT DO NOTHING
`

type AddAppointmentServicesBulkParams struct {
	TenantID      uuid.UUID   `json:"tenant_id"`
	AppointmentID uuid.UUID   `json:"appointment_id"`
	ServiceIds    []uuid.UUID `json:"service_ids"`
}

// 一次插入多条 appointment_services；ON CONFLICT 兼容入参重复 id
func (q *Queries) AddAppointmentServicesBulk(ctx context.Context, arg AddAppointmentServicesBulkParams) error {
	_, err := q.db.Exec(ctx, addAppointmentServicesBulk, arg.TenantID, arg.AppointmentID, arg.ServiceIds)
	return err
}

const clearAppointmentServices = `-- name: ClearAppointmentServices :exec
DELETE FROM appointment_services WHERE appointment_id = $1
`

func (q *Queries) ClearAppointmentServices(ctx context.Context, appointmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAppointmentServices, appointmentID)
	return err
}

const countAppointmentsInRange = `-- name: CountAppointmentsInRange :one
SELECT count(*) FROM appointments
WHERE appointment_time >= $1 AND appointment_time < $2
  AND status IN ('pending', 'confirmed')
`

type CountAppointmentsInRangeParams struct {
	AppointmentTime   pgtype.Timestamptz `json:"appointment_time"`
	AppointmentTime_2 pgtype.Timestamptz `json:"appointment_time_2"`
}

// 今日/范围内预约计数（仅 pending+confirmed）
func (q *Queries) CountAppointmentsInRange(ctx context.Context, arg CountAppointmentsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointmentsInRange, arg.AppointmentTime, arg.AppointmentTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPhoneConflicts = `-- name: CountPhoneConflicts :one
SELECT count(*) FROM appointments
WHERE customer_phone = $1
  AND appointment_time >= $2
  AND appointment_time <= $3
  AND status IN ('pending', 'confirmed')
`

type CountPhoneConflictsParams struct {
	CustomerPhone     string             `json:"customer_phone"`
	AppointmentTime   pgtype.Timestamptz `json:"appointment_time"`
	AppointmentTime_2 pgtype.Timestamptz `json:"appointment_time_2"`
}

// 同手机号在时间窗内已有 pending/confirmed 预约
func (q *Queries) CountPhoneConflicts(ctx context.Context, arg CountPhoneConflictsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhoneConflicts, arg.CustomerPhone, arg.AppointmentTime, arg.AppointmentTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaffConflicts = `-- name: CountStaffConflicts :one
SELECT count(*) FROM appointments
WHERE assigned_staff_id = $1
  AND appointment_time >= $2
  AND appointment_time <= $3
  AND status IN ('pending', 'confirmed')
`

type CountStaffConflictsParams struct {
	AssignedStaffID   pgtype.UUID        `json:"assigned_staff_id"`
	AppointmentTime   pgtype.Timestamptz `json:"appointment_time"`
	AppointmentTime_2 pgtype.Timestamptz `json:"appointment_time_2"`
}

func (q *Queries) CountStaffConflicts(ctx context.Context, arg CountStaffConflictsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStaffConflicts, arg.AssignedStaffID, arg.AppointmentTime, arg.AppointmentTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
  tenant_id, member_id, customer_name, customer_phone,
  appointment_time, assigned_staff_id, status, source, notes
) VALUES (
  $1,
  $5::uuid,
  $2, $3, $4,
  $6::uuid,
  COALESCE($7::text, 'pending'),
  COALESCE($8::text, 'staff'),
  $9::text
) RETURNING id, tenant_id, member_id, customer_name, customer_phone, appointment_time, assigned_staff_id, status, transaction_id, source, notes, legacy_id, created_at, updated_at
`

type CreateAppointmentParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	CustomerName    string             `json:"customer_name"`
	CustomerPhone   string             `json:"customer_phone"`
	AppointmentTime pgtype.Timestamptz `json:"appointment_time"`
	MemberID        pgtype.UUID        `json:"member_id"`
	AssignedStaffID pgtype.UUID        `json:"assigned_staff_id"`
	Status          *string            `json:"status"`
	Source          *string            `json:"source"`
	Notes           *string            `json:"notes"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.TenantID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.AppointmentTime,
		arg.MemberID,
		arg.AssignedStaffID,
		arg.Status,
		arg.Source,
		arg.Notes,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.AppointmentTime,
		&i.AssignedStaffID,
		&i.Status,
		&i.TransactionID,
		&i.Source,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointment, id)
	return err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, tenant_id, member_id, customer_name, customer_phone, appointment_time, assigned_staff_id, status, transaction_id, source, notes, legacy_id, created_at, updated_at FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.AppointmentTime,
		&i.AssignedStaffID,
		&i.Status,
		&i.TransactionID,
		&i.Source,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointmentServices = `-- name: ListAppointmentServices :many
SELECT s.id, s.name, s.price
FROM appointment_services aps
JOIN services s ON s.id = aps.service_id
WHERE aps.appointment_id = $1
ORDER BY s.sort_order ASC, s.name ASC
`

type ListAppointmentServicesRow struct {
	ID    uuid.UUID       `json:"id"`
	Name  string          `json:"name"`
	Price decimal.Decimal `json:"price"`
}

func (q *Queries) ListAppointmentServices(ctx context.Context, appointmentID uuid.UUID) ([]ListAppointmentServicesRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentServices, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentServicesRow
	for rows.Next() {
		var i ListAppointmentServicesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, tenant_id, member_id, customer_name, customer_phone, appointment_time, assigned_staff_id, status, transaction_id, source, notes, legacy_id, created_at, updated_at FROM appointments
WHERE ($1::timestamptz IS NULL OR appointment_time >= $1::timestamptz)
  AND ($2::timestamptz   IS NULL OR appointment_time <  $2::timestamptz)
  AND ($3::uuid          IS NULL OR assigned_staff_id = $3::uuid)
  AND ($4::text            IS NULL OR status            = $4::text)
ORDER BY
  CASE status
    WHEN 'pending'   THEN 0
    WHEN 'confirmed' THEN 1
    WHEN 'completed' THEN 2
    WHEN 'no_show'   THEN 3
    WHEN 'cancelled' THEN 4
    ELSE 5
  END,
  appointment_time ASC
`

type ListAppointmentsParams struct {
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	StaffID   pgtype.UUID        `json:"staff_id"`
	Status    *string            `json:"status"`
}

func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments,
		arg.StartDate,
		arg.EndDate,
		arg.StaffID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemberID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.AppointmentTime,
			&i.AssignedStaffID,
			&i.Status,
			&i.TransactionID,
			&i.Source,
			&i.Notes,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAppointmentsByIDs = `-- name: LookupAppointmentsByIDs :many
SELECT id, customer_name, appointment_time FROM appointments WHERE id = ANY($1::uuid[])
`

type LookupAppointmentsByIDsRow struct {
	ID              uuid.UUID          `json:"id"`
	CustomerName    string             `json:"customer_name"`
	AppointmentTime pgtype.Timestamptz `json:"appointment_time"`
}

// 批量返回 id + 顾客姓名（给操作日志对象列显示用）
func (q *Queries) LookupAppointmentsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]LookupAppointmentsByIDsRow, error) {
	rows, err := q.db.Query(ctx, lookupAppointmentsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupAppointmentsByIDsRow
	for rows.Next() {
		var i LookupAppointmentsByIDsRow
		if err := rows.Scan(&i.ID, &i.CustomerName, &i.AppointmentTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, member_id, customer_name, customer_phone, appointment_time, assigned_staff_id, status, transaction_id, source, notes, legacy_id, created_at, updated_at
`

type UpdateAppointmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentStatus, arg.ID, arg.Status)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.AppointmentTime,
		&i.AssignedStaffID,
		&i.Status,
		&i.TransactionID,
		&i.Source,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
