// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
  tenant_id, actor_id, actor_type, action, target_type, target_id, payload, ip_address, user_agent
) VALUES (
  $1, $2, $3, $4,
  $6::text,
  $7::text,
  $5,
  $8::inet,
  $9::text
)
`

type CreateAuditLogParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorType  string      `json:"actor_type"`
	Action     string      `json:"action"`
	Payload    []byte      `json:"payload"`
	TargetType *string     `json:"target_type"`
	TargetID   *string     `json:"target_id"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  *string     `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.Payload,
		arg.TargetType,
		arg.TargetID,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
  a.id, a.tenant_id, a.actor_id, a.actor_type, a.action, a.target_type, a.target_id, a.payload, a.ip_address, a.user_agent, a.created_at,
  u.name AS actor_name
FROM audit_logs a
LEFT JOIN users u ON u.id = a.actor_id
WHERE ($3::uuid IS NULL OR a.tenant_id = $3::uuid)
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListAuditLogsRow struct {
	ID         int64              `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorType  string             `json:"actor_type"`
	Action     string             `json:"action"`
	TargetType *string            `json:"target_type"`
	TargetID   *string            `json:"target_id"`
	Payload    []byte             `json:"payload"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  *string            `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ActorName  *string            `json:"actor_name"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
