// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card_balance_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const adjustCardBalance = `-- name: AdjustCardBalance :one
UPDATE cards
SET balance = balance + $2,
    updated_at = now()
WHERE id = $1
  AND balance + $2 >= 0
RETURNING id, tenant_id, member_id, card_type_id, final_price, final_discount_rate, balance, issued_at, expires_at, status, notes, legacy_id, created_at, updated_at
`

type AdjustCardBalanceParams struct {
	ID      uuid.UUID       `json:"id"`
	Balance decimal.Decimal `json:"balance"`
}

// 原子地给 cards.balance 加上 delta（负数即扣款），并带乐观检查（不许扣成负数）
func (q *Queries) AdjustCardBalance(ctx context.Context, arg AdjustCardBalanceParams) (Card, error) {
	row := q.db.QueryRow(ctx, adjustCardBalance, arg.ID, arg.Balance)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.CardTypeID,
		&i.FinalPrice,
		&i.FinalDiscountRate,
		&i.Balance,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCardBalanceLog = `-- name: CreateCardBalanceLog :one
INSERT INTO card_balance_logs (
  tenant_id, card_id, transaction_id,
  change_type, delta, balance_before, balance_after,
  operator_user_id, note
) VALUES (
  $1, $2,
  $7::uuid,
  $3, $4, $5, $6,
  $8::uuid,
  $9::text
) RETURNING id, tenant_id, card_id, transaction_id, change_type, delta, balance_before, balance_after, operator_user_id, note, occurred_at, created_at
`

type CreateCardBalanceLogParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	CardID         uuid.UUID       `json:"card_id"`
	ChangeType     string          `json:"change_type"`
	Delta          decimal.Decimal `json:"delta"`
	BalanceBefore  decimal.Decimal `json:"balance_before"`
	BalanceAfter   decimal.Decimal `json:"balance_after"`
	TransactionID  pgtype.UUID     `json:"transaction_id"`
	OperatorUserID pgtype.UUID     `json:"operator_user_id"`
	Note           *string         `json:"note"`
}

func (q *Queries) CreateCardBalanceLog(ctx context.Context, arg CreateCardBalanceLogParams) (CardBalanceLog, error) {
	row := q.db.QueryRow(ctx, createCardBalanceLog,
		arg.TenantID,
		arg.CardID,
		arg.ChangeType,
		arg.Delta,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.TransactionID,
		arg.OperatorUserID,
		arg.Note,
	)
	var i CardBalanceLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CardID,
		&i.TransactionID,
		&i.ChangeType,
		&i.Delta,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.OperatorUserID,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCardBalanceLogsByTx = `-- name: ListCardBalanceLogsByTx :many
SELECT id, tenant_id, card_id, transaction_id, change_type, delta, balance_before, balance_after, operator_user_id, note, occurred_at, created_at FROM card_balance_logs
WHERE transaction_id = $1
ORDER BY occurred_at ASC
`

func (q *Queries) ListCardBalanceLogsByTx(ctx context.Context, transactionID pgtype.UUID) ([]CardBalanceLog, error) {
	rows, err := q.db.Query(ctx, listCardBalanceLogsByTx, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardBalanceLog
	for rows.Next() {
		var i CardBalanceLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CardID,
			&i.TransactionID,
			&i.ChangeType,
			&i.Delta,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.OperatorUserID,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardSnapshotsByTxIDs = `-- name: ListCardSnapshotsByTxIDs :many
SELECT
  l.transaction_id,
  l.card_id,
  l.balance_before,
  l.balance_after,
  l.delta,
  l.change_type,
  (CASE WHEN c.final_price <> ct.price
             THEN '自定义面值卡(¥' || to_char(c.final_price, 'FM9999999990.00') || ')'
             ELSE ct.name END
        || CASE WHEN c.final_discount_rate < 1
             THEN ' ' || rtrim(rtrim(to_char(c.final_discount_rate * 10, 'FM90.9'), '0'), '.') || '折'
             ELSE '' END)::text AS card_type_name
FROM card_balance_logs l
JOIN cards c       ON c.id = l.card_id
JOIN card_types ct ON ct.id = c.card_type_id
WHERE l.transaction_id = ANY($1::uuid[])
ORDER BY l.transaction_id, l.occurred_at ASC
`

type ListCardSnapshotsByTxIDsRow struct {
	TransactionID pgtype.UUID     `json:"transaction_id"`
	CardID        uuid.UUID       `json:"card_id"`
	BalanceBefore decimal.Decimal `json:"balance_before"`
	BalanceAfter  decimal.Decimal `json:"balance_after"`
	Delta         decimal.Decimal `json:"delta"`
	ChangeType    string          `json:"change_type"`
	CardTypeName  string          `json:"card_type_name"`
}

// 批量取多笔交易的卡余额快照（POS 今日记录 hover 显示用）
// 同时 join 卡类型名，前端不需二次查询
func (q *Queries) ListCardSnapshotsByTxIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCardSnapshotsByTxIDsRow, error) {
	rows, err := q.db.Query(ctx, listCardSnapshotsByTxIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardSnapshotsByTxIDsRow
	for rows.Next() {
		var i ListCardSnapshotsByTxIDsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.CardID,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Delta,
			&i.ChangeType,
			&i.CardTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
