// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const issueCard = `-- name: IssueCard :one
INSERT INTO cards (
  tenant_id, member_id, card_type_id,
  final_price, final_discount_rate, balance,
  expires_at, notes
)
VALUES (
  $1, $2, $3, $4, $5,
  COALESCE($6::numeric, $4),
  $7::timestamptz,
  $8::text
)
RETURNING id, tenant_id, member_id, card_type_id, final_price, final_discount_rate, balance, issued_at, expires_at, status, notes, legacy_id, created_at, updated_at
`

type IssueCardParams struct {
	TenantID          uuid.UUID           `json:"tenant_id"`
	MemberID          uuid.UUID           `json:"member_id"`
	CardTypeID        uuid.UUID           `json:"card_type_id"`
	FinalPrice        decimal.Decimal     `json:"final_price"`
	FinalDiscountRate decimal.Decimal     `json:"final_discount_rate"`
	Balance           decimal.NullDecimal `json:"balance"`
	ExpiresAt         pgtype.Timestamptz  `json:"expires_at"`
	Notes             *string             `json:"notes"`
}

// 最小单元：只建 card 不建 transaction（开卡+收款联动由 handler 层组合）
// balance 默认 = final_price；调用方也可显式传（比如迁移时保留老余额）
func (q *Queries) IssueCard(ctx context.Context, arg IssueCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, issueCard,
		arg.TenantID,
		arg.MemberID,
		arg.CardTypeID,
		arg.FinalPrice,
		arg.FinalDiscountRate,
		arg.Balance,
		arg.ExpiresAt,
		arg.Notes,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.CardTypeID,
		&i.FinalPrice,
		&i.FinalDiscountRate,
		&i.Balance,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByMember = `-- name: ListCardsByMember :many
SELECT
  c.id, c.tenant_id, c.member_id, c.card_type_id,
  c.final_price, c.final_discount_rate, c.balance,
  c.issued_at, c.expires_at, c.status, c.notes,
  c.legacy_id, c.created_at, c.updated_at,
  ct.name          AS card_type_name,
  ct.price         AS card_type_price,
  ct.discount_rate AS card_type_discount_rate
FROM cards c
JOIN card_types ct ON ct.id = c.card_type_id
WHERE c.member_id = $1
ORDER BY c.issued_at DESC
`

type ListCardsByMemberRow struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	MemberID             uuid.UUID          `json:"member_id"`
	CardTypeID           uuid.UUID          `json:"card_type_id"`
	FinalPrice           decimal.Decimal    `json:"final_price"`
	FinalDiscountRate    decimal.Decimal    `json:"final_discount_rate"`
	Balance              decimal.Decimal    `json:"balance"`
	IssuedAt             pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Status               string             `json:"status"`
	Notes                *string            `json:"notes"`
	LegacyID             *string            `json:"legacy_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CardTypeName         string             `json:"card_type_name"`
	CardTypePrice        decimal.Decimal    `json:"card_type_price"`
	CardTypeDiscountRate decimal.Decimal    `json:"card_type_discount_rate"`
}

// 会员名下的所有卡，附带卡型模板字段（前端显示用）
func (q *Queries) ListCardsByMember(ctx context.Context, memberID uuid.UUID) ([]ListCardsByMemberRow, error) {
	rows, err := q.db.Query(ctx, listCardsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsByMemberRow
	for rows.Next() {
		var i ListCardsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemberID,
			&i.CardTypeID,
			&i.FinalPrice,
			&i.FinalDiscountRate,
			&i.Balance,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Notes,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CardTypeName,
			&i.CardTypePrice,
			&i.CardTypeDiscountRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByMemberForUpdate = `-- name: ListCardsByMemberForUpdate :many
SELECT c.id, c.member_id, c.final_discount_rate, c.balance, c.status, c.expires_at,
       ct.name AS card_type_name
FROM cards c
JOIN card_types ct ON ct.id = c.card_type_id
WHERE c.member_id = $1
ORDER BY c.id
FOR UPDATE OF c
`

type ListCardsByMemberForUpdateRow struct {
	ID                uuid.UUID          `json:"id"`
	MemberID          uuid.UUID          `json:"member_id"`
	FinalDiscountRate decimal.Decimal    `json:"final_discount_rate"`
	Balance           decimal.Decimal    `json:"balance"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CardTypeName      string             `json:"card_type_name"`
}

// 挂账定价路径：先锁会员全部卡再取折扣率，防并发把卡扣空/作废后仍按旧折扣入账
// 带 member_id / card_type_name：挂账分支的扣卡校验直接复用锁行，不再二次 SELECT
// ORDER BY c.id 与 LockCardsForUpdate 同序加锁，防死锁
func (q *Queries) ListCardsByMemberForUpdate(ctx context.Context, memberID uuid.UUID) ([]ListCardsByMemberForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listCardsByMemberForUpdate, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsByMemberForUpdateRow
	for rows.Next() {
		var i ListCardsByMemberForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.FinalDiscountRate,
			&i.Balance,
			&i.Status,
			&i.ExpiresAt,
			&i.CardTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCardForUpdate = `-- name: LockCardForUpdate :one
SELECT
  c.id, c.tenant_id, c.member_id, c.card_type_id,
  c.final_price, c.final_discount_rate, c.balance,
  c.issued_at, c.expires_at, c.status, c.notes,
  c.legacy_id, c.created_at, c.updated_at,
  ct.name          AS card_type_name,
  ct.price         AS card_type_price,
  ct.discount_rate AS card_type_discount_rate
FROM cards c
JOIN card_types ct ON ct.id = c.card_type_id
WHERE c.id = $1
FOR UPDATE OF c
`

type LockCardForUpdateRow struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	MemberID             uuid.UUID          `json:"member_id"`
	CardTypeID           uuid.UUID          `json:"card_type_id"`
	FinalPrice           decimal.Decimal    `json:"final_price"`
	FinalDiscountRate    decimal.Decimal    `json:"final_discount_rate"`
	Balance              decimal.Decimal    `json:"balance"`
	IssuedAt             pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Status               string             `json:"status"`
	Notes                *string            `json:"notes"`
	LegacyID             *string            `json:"legacy_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CardTypeName         string             `json:"card_type_name"`
	CardTypePrice        decimal.Decimal    `json:"card_type_price"`
	CardTypeDiscountRate decimal.Decimal    `json:"card_type_discount_rate"`
}

// 扣款路径专用：SELECT FOR UPDATE 锁单行，防并发双扣
// 注：JOIN 的 card_types 不加锁（只读关联）
func (q *Queries) LockCardForUpdate(ctx context.Context, id uuid.UUID) (LockCardForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockCardForUpdate, id)
	var i LockCardForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.CardTypeID,
		&i.FinalPrice,
		&i.FinalDiscountRate,
		&i.Balance,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardTypeName,
		&i.CardTypePrice,
		&i.CardTypeDiscountRate,
	)
	return i, err
}

const lockCardsForUpdate = `-- name: LockCardsForUpdate :many
SELECT
  c.id, c.tenant_id, c.member_id, c.card_type_id,
  c.final_price, c.final_discount_rate, c.balance,
  c.issued_at, c.expires_at, c.status, c.notes,
  c.legacy_id, c.created_at, c.updated_at,
  ct.name          AS card_type_name,
  ct.price         AS card_type_price,
  ct.discount_rate AS card_type_discount_rate
FROM cards c
JOIN card_types ct ON ct.id = c.card_type_id
WHERE c.id = ANY($1::uuid[])
ORDER BY c.id
FOR UPDATE OF c
`

type LockCardsForUpdateRow struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	MemberID             uuid.UUID          `json:"member_id"`
	CardTypeID           uuid.UUID          `json:"card_type_id"`
	FinalPrice           decimal.Decimal    `json:"final_price"`
	FinalDiscountRate    decimal.Decimal    `json:"final_discount_rate"`
	Balance              decimal.Decimal    `json:"balance"`
	IssuedAt             pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Status               string             `json:"status"`
	Notes                *string            `json:"notes"`
	LegacyID             *string            `json:"legacy_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CardTypeName         string             `json:"card_type_name"`
	CardTypePrice        decimal.Decimal    `json:"card_type_price"`
	CardTypeDiscountRate decimal.Decimal    `json:"card_type_discount_rate"`
}

// 多卡支付路径：一次性锁所有目标卡，避免 N+1 RTT
// ORDER BY c.id 关键：所有事务用同序加锁，防死锁
// 调用方需在传入 ids 前自行排序（或保证传入顺序确定）
func (q *Queries) LockCardsForUpdate(ctx context.Context, ids []uuid.UUID) ([]LockCardsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, lockCardsForUpdate, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockCardsForUpdateRow
	for rows.Next() {
		var i LockCardsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemberID,
			&i.CardTypeID,
			&i.FinalPrice,
			&i.FinalDiscountRate,
			&i.Balance,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Notes,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CardTypeName,
			&i.CardTypePrice,
			&i.CardTypeDiscountRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET final_price         = COALESCE($2::numeric,         final_price),
    final_discount_rate = COALESCE($3::numeric, final_discount_rate),
    status              = COALESCE($4::text,                 status),
    expires_at          = COALESCE($5::timestamptz,      expires_at),
    notes               = COALESCE($6::text,                  notes),
    updated_at          = now()
WHERE id = $1
RETURNING id, tenant_id, member_id, card_type_id, final_price, final_discount_rate, balance, issued_at, expires_at, status, notes, legacy_id, created_at, updated_at
`

type UpdateCardParams struct {
	ID                uuid.UUID           `json:"id"`
	FinalPrice        decimal.NullDecimal `json:"final_price"`
	FinalDiscountRate decimal.NullDecimal `json:"final_discount_rate"`
	Status            *string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz  `json:"expires_at"`
	Notes             *string             `json:"notes"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.ID,
		arg.FinalPrice,
		arg.FinalDiscountRate,
		arg.Status,
		arg.ExpiresAt,
		arg.Notes,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.CardTypeID,
		&i.FinalPrice,
		&i.FinalDiscountRate,
		&i.Balance,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
