// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card_types.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countCardTypeUsage = `-- name: CountCardTypeUsage :one
SELECT count(*) FROM cards WHERE card_type_id = $1
`

func (q *Queries) CountCardTypeUsage(ctx context.Context, cardTypeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCardTypeUsage, cardTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCardType = `-- name: CreateCardType :one
INSERT INTO card_types (tenant_id, name, price, discount_rate, sort_order)
VALUES ($1, $2, $3, $4, COALESCE($5::int, 99))
RETURNING id, tenant_id, name, price, discount_rate, sort_order, status, legacy_id, created_at, updated_at
`

type CreateCardTypeParams struct {
	TenantID     uuid.UUID       `json:"tenant_id"`
	Name         string          `json:"name"`
	Price        decimal.Decimal `json:"price"`
	DiscountRate decimal.Decimal `json:"discount_rate"`
	SortOrder    *int32          `json:"sort_order"`
}

func (q *Queries) CreateCardType(ctx context.Context, arg CreateCardTypeParams) (CardType, error) {
	row := q.db.QueryRow(ctx, createCardType,
		arg.TenantID,
		arg.Name,
		arg.Price,
		arg.DiscountRate,
		arg.SortOrder,
	)
	var i CardType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Price,
		&i.DiscountRate,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCardType = `-- name: DeleteCardType :exec
DELETE FROM card_types WHERE id = $1
`

func (q *Queries) DeleteCardType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCardType, id)
	return err
}

const getCardTypeByID = `-- name: GetCardTypeByID :one
SELECT id, tenant_id, name, price, discount_rate, sort_order, status, legacy_id, created_at, updated_at FROM card_types WHERE id = $1
`

func (q *Queries) GetCardTypeByID(ctx context.Context, id uuid.UUID) (CardType, error) {
	row := q.db.QueryRow(ctx, getCardTypeByID, id)
	var i CardType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Price,
		&i.DiscountRate,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardTypes = `-- name: ListCardTypes :many
SELECT id, tenant_id, name, price, discount_rate, sort_order, status, legacy_id, created_at, updated_at FROM card_types
WHERE status = COALESCE($1::text, status)
ORDER BY sort_order ASC, price ASC
`

func (q *Queries) ListCardTypes(ctx context.Context, status *string) ([]CardType, error) {
	rows, err := q.db.Query(ctx, listCardTypes, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardType
	for rows.Next() {
		var i CardType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Price,
			&i.DiscountRate,
			&i.SortOrder,
			&i.Status,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardType = `-- name: UpdateCardType :one
UPDATE card_types
SET name          = COALESCE($2::text,          name),
    price         = COALESCE($3::numeric,      price),
    discount_rate = COALESCE($4::numeric, discount_rate),
    sort_order    = COALESCE($5::int,     sort_order),
    status        = COALESCE($6::text,        status),
    updated_at    = now()
WHERE id = $1
RETURNING id, tenant_id, name, price, discount_rate, sort_order, status, legacy_id, created_at, updated_at
`

type UpdateCardTypeParams struct {
	ID           uuid.UUID           `json:"id"`
	Name         *string             `json:"name"`
	Price        decimal.NullDecimal `json:"price"`
	DiscountRate decimal.NullDecimal `json:"discount_rate"`
	SortOrder    *int32              `json:"sort_order"`
	Status       *string             `json:"status"`
}

func (q *Queries) UpdateCardType(ctx context.Context, arg UpdateCardTypeParams) (CardType, error) {
	row := q.db.QueryRow(ctx, updateCardType,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.DiscountRate,
		arg.SortOrder,
		arg.Status,
	)
	var i CardType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Price,
		&i.DiscountRate,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
