// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commission_rules.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createCommissionRule = `-- name: CreateCommissionRule :one
INSERT INTO commission_rules (
  tenant_id, staff_id, service_id, rate, fixed_amount, note
) VALUES (
  $1, $2,
  $3::uuid,
  $4::numeric,
  $5::numeric,
  $6::text
) RETURNING id, tenant_id, staff_id, service_id, rate, fixed_amount, note, created_at, updated_at
`

type CreateCommissionRuleParams struct {
	TenantID    uuid.UUID           `json:"tenant_id"`
	StaffID     uuid.UUID           `json:"staff_id"`
	ServiceID   pgtype.UUID         `json:"service_id"`
	Rate        decimal.NullDecimal `json:"rate"`
	FixedAmount decimal.NullDecimal `json:"fixed_amount"`
	Note        *string             `json:"note"`
}

func (q *Queries) CreateCommissionRule(ctx context.Context, arg CreateCommissionRuleParams) (CommissionRule, error) {
	row := q.db.QueryRow(ctx, createCommissionRule,
		arg.TenantID,
		arg.StaffID,
		arg.ServiceID,
		arg.Rate,
		arg.FixedAmount,
		arg.Note,
	)
	var i CommissionRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.Rate,
		&i.FixedAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCommissionRule = `-- name: DeleteCommissionRule :exec
DELETE FROM commission_rules WHERE id = $1
`

func (q *Queries) DeleteCommissionRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommissionRule, id)
	return err
}

const getCommissionRuleByID = `-- name: GetCommissionRuleByID :one
SELECT id, tenant_id, staff_id, service_id, rate, fixed_amount, note, created_at, updated_at FROM commission_rules WHERE id = $1
`

func (q *Queries) GetCommissionRuleByID(ctx context.Context, id uuid.UUID) (CommissionRule, error) {
	row := q.db.QueryRow(ctx, getCommissionRuleByID, id)
	var i CommissionRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.Rate,
		&i.FixedAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommissionRules = `-- name: ListCommissionRules :many
SELECT
  cr.id, cr.tenant_id, cr.staff_id, cr.service_id, cr.rate, cr.fixed_amount, cr.note,
  cr.created_at, cr.updated_at,
  s.name AS staff_name,
  sv.name AS service_name
FROM commission_rules cr
JOIN staff s ON s.id = cr.staff_id
LEFT JOIN services sv ON sv.id = cr.service_id
WHERE ($1::uuid IS NULL OR cr.staff_id = $1::uuid)
ORDER BY s.sort_order ASC, s.name ASC, sv.sort_order ASC NULLS FIRST
`

type ListCommissionRulesRow struct {
	ID          uuid.UUID           `json:"id"`
	TenantID    uuid.UUID           `json:"tenant_id"`
	StaffID     uuid.UUID           `json:"staff_id"`
	ServiceID   pgtype.UUID         `json:"service_id"`
	Rate        decimal.NullDecimal `json:"rate"`
	FixedAmount decimal.NullDecimal `json:"fixed_amount"`
	Note        *string             `json:"note"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
	StaffName   string              `json:"staff_name"`
	ServiceName *string             `json:"service_name"`
}

// 可按 staff_id 过滤
func (q *Queries) ListCommissionRules(ctx context.Context, staffID pgtype.UUID) ([]ListCommissionRulesRow, error) {
	rows, err := q.db.Query(ctx, listCommissionRules, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommissionRulesRow
	for rows.Next() {
		var i ListCommissionRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StaffID,
			&i.ServiceID,
			&i.Rate,
			&i.FixedAmount,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StaffName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommissionRule = `-- name: UpdateCommissionRule :one
UPDATE commission_rules
SET rate         = COALESCE($2::numeric,         rate),
    fixed_amount = COALESCE($3::numeric, fixed_amount),
    note         = COALESCE($4::text,            note),
    updated_at   = now()
WHERE id = $1
RETURNING id, tenant_id, staff_id, service_id, rate, fixed_amount, note, created_at, updated_at
`

type UpdateCommissionRuleParams struct {
	ID          uuid.UUID           `json:"id"`
	Rate        decimal.NullDecimal `json:"rate"`
	FixedAmount decimal.NullDecimal `json:"fixed_amount"`
	Note        *string             `json:"note"`
}

func (q *Queries) UpdateCommissionRule(ctx context.Context, arg UpdateCommissionRuleParams) (CommissionRule, error) {
	row := q.db.QueryRow(ctx, updateCommissionRule,
		arg.ID,
		arg.Rate,
		arg.FixedAmount,
		arg.Note,
	)
	var i CommissionRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.Rate,
		&i.FixedAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
