// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: editions.sql

package sqlc

import (
	"context"
)

const getEditionByCode = `-- name: GetEditionByCode :one
SELECT id, code, name, price_monthly, price_yearly, quotas, features, sort_order, active, created_at, updated_at FROM editions WHERE code = $1
`

func (q *Queries) GetEditionByCode(ctx context.Context, code string) (Edition, error) {
	row := q.db.QueryRow(ctx, getEditionByCode, code)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Quotas,
		&i.Features,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEditionByID = `-- name: GetEditionByID :one
SELECT id, code, name, price_monthly, price_yearly, quotas, features, sort_order, active, created_at, updated_at FROM editions WHERE id = $1
`

func (q *Queries) GetEditionByID(ctx context.Context, id int16) (Edition, error) {
	row := q.db.QueryRow(ctx, getEditionByID, id)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Quotas,
		&i.Features,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveEditions = `-- name: ListActiveEditions :many
SELECT id, code, name, price_monthly, price_yearly, quotas, features, sort_order, active, created_at, updated_at FROM editions
WHERE active = TRUE
ORDER BY sort_order
`

func (q *Queries) ListActiveEditions(ctx context.Context) ([]Edition, error) {
	rows, err := q.db.Query(ctx, listActiveEditions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edition
	for rows.Next() {
		var i Edition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.PriceMonthly,
			&i.PriceYearly,
			&i.Quotas,
			&i.Features,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
