// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM members
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL
       OR name  ILIKE '%' || $2::text || '%'
       OR phone LIKE  '%' || $2::text || '%')
`

type CountMembersParams struct {
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) CountMembers(ctx context.Context, arg CountMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (tenant_id, name, phone, gender, birthday, notes)
VALUES ($1, $2, $3, COALESCE($6::text, 'unknown'), $4, $5)
RETURNING id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at, legacy_id
`

type CreateMemberParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     string      `json:"name"`
	Phone    *string     `json:"phone"`
	Birthday pgtype.Date `json:"birthday"`
	Notes    *string     `json:"notes"`
	Gender   *string     `json:"gender"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.TenantID,
		arg.Name,
		arg.Phone,
		arg.Birthday,
		arg.Notes,
		arg.Gender,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegacyID,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const existsMemberByPhone = `-- name: ExistsMemberByPhone :one
SELECT EXISTS (
  SELECT 1 FROM members
  WHERE phone = $1::text
    AND ($2::uuid IS NULL OR id <> $2::uuid)
) AS "exists"
`

type ExistsMemberByPhoneParams struct {
	Phone     string      `json:"phone"`
	ExcludeID pgtype.UUID `json:"exclude_id"`
}

// 手机号唯一性检查（占位号 '00000000000' 允许重复，由 handler 跳过）
// exclude_id：编辑时排除自己
func (q *Queries) ExistsMemberByPhone(ctx context.Context, arg ExistsMemberByPhoneParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsMemberByPhone, arg.Phone, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at, legacy_id FROM members WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegacyID,
	)
	return i, err
}

const getMemberStats = `-- name: GetMemberStats :one
SELECT
  COALESCE((SELECT SUM(c.balance) FROM cards c WHERE c.member_id = $1 AND c.status = 'active'), 0)::numeric AS total_balance,
  COALESCE((SELECT SUM(mc.amount) FROM member_credits mc WHERE mc.member_id = $1 AND mc.settled_at IS NULL), 0)::numeric AS total_pending,
  (SELECT COUNT(*) FROM cards c WHERE c.member_id = $1 AND c.status = 'active')::bigint AS card_count,
  (SELECT COUNT(*) FROM cards c WHERE c.member_id = $1 AND c.status = 'active' AND c.balance > 0)::bigint AS active_card_count
`

type GetMemberStatsRow struct {
	TotalBalance    decimal.Decimal `json:"total_balance"`
	TotalPending    decimal.Decimal `json:"total_pending"`
	CardCount       int64           `json:"card_count"`
	ActiveCardCount int64           `json:"active_card_count"`
}

// 单查会员的聚合字段，口径与 ListMembers 一致（active 卡余额 + 未清挂账）
func (q *Queries) GetMemberStats(ctx context.Context, memberID uuid.UUID) (GetMemberStatsRow, error) {
	row := q.db.QueryRow(ctx, getMemberStats, memberID)
	var i GetMemberStatsRow
	err := row.Scan(
		&i.TotalBalance,
		&i.TotalPending,
		&i.CardCount,
		&i.ActiveCardCount,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT
  m.id, m.tenant_id, m.name, m.phone, m.gender, m.birthday, m.notes, m.status,
  m.created_at, m.updated_at, m.legacy_id,
  COALESCE(cb.total_balance, 0)::numeric AS total_balance,
  COALESCE(pc.total_pending, 0)::numeric AS total_pending,
  COALESCE(cb.card_count, 0)::bigint     AS card_count,
  COALESCE(cb.active_card_count, 0)::bigint AS active_card_count
FROM members m
LEFT JOIN (
  SELECT member_id,
         SUM(balance)::numeric AS total_balance,
         COUNT(*)::bigint AS card_count,
         COUNT(*) FILTER (WHERE balance > 0)::bigint AS active_card_count
  FROM cards WHERE status = 'active' GROUP BY member_id
) cb ON cb.member_id = m.id
LEFT JOIN (
  SELECT member_id, SUM(amount)::numeric AS total_pending
  FROM member_credits WHERE settled_at IS NULL GROUP BY member_id
) pc ON pc.member_id = m.id
WHERE ($3::text IS NULL OR m.status = $3::text)
  AND ($4::text IS NULL
       OR m.name  ILIKE '%' || $4::text || '%'
       OR m.phone LIKE  '%' || $4::text || '%')
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type ListMembersParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
	Search *string `json:"search"`
}

type ListMembersRow struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Name            string             `json:"name"`
	Phone           *string            `json:"phone"`
	Gender          string             `json:"gender"`
	Birthday        pgtype.Date        `json:"birthday"`
	Notes           *string            `json:"notes"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LegacyID        *string            `json:"legacy_id"`
	TotalBalance    decimal.Decimal    `json:"total_balance"`
	TotalPending    decimal.Decimal    `json:"total_pending"`
	CardCount       int64              `json:"card_count"`
	ActiveCardCount int64              `json:"active_card_count"`
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Phone,
			&i.Gender,
			&i.Birthday,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LegacyID,
			&i.TotalBalance,
			&i.TotalPending,
			&i.CardCount,
			&i.ActiveCardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupMembersByIDs = `-- name: LookupMembersByIDs :many
SELECT id, name FROM members WHERE id = ANY($1::uuid[])
`

type LookupMembersByIDsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// 按一组 ID 批量返回 id→name（用于操作日志对象列人名化）
func (q *Queries) LookupMembersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]LookupMembersByIDsRow, error) {
	rows, err := q.db.Query(ctx, lookupMembersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupMembersByIDsRow
	for rows.Next() {
		var i LookupMembersByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET name       = COALESCE($2::text,    name),
    phone      = COALESCE($3::text,   phone),
    gender     = COALESCE($4::text,  gender),
    birthday   = COALESCE($5::date, birthday),
    notes      = COALESCE($6::text,   notes),
    status     = COALESCE($7::text,  status),
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at, legacy_id
`

type UpdateMemberParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     *string     `json:"name"`
	Phone    *string     `json:"phone"`
	Gender   *string     `json:"gender"`
	Birthday pgtype.Date `json:"birthday"`
	Notes    *string     `json:"notes"`
	Status   *string     `json:"status"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Gender,
		arg.Birthday,
		arg.Notes,
		arg.Status,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegacyID,
	)
	return i, err
}
