// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member_credits.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createCredit = `-- name: CreateCredit :one
INSERT INTO member_credits (
  tenant_id, member_id, amount, summary, charged_at, charged_tx_id
)
VALUES (
  $1, $2, $3,
  $4::text,
  COALESCE($5::timestamptz, now()),
  $6::uuid
)
RETURNING id, tenant_id, member_id, amount, summary, charged_at, charged_tx_id, settled_at, settlement_tx_id, legacy_id, created_at, updated_at
`

type CreateCreditParams struct {
	TenantID    uuid.UUID          `json:"tenant_id"`
	MemberID    uuid.UUID          `json:"member_id"`
	Amount      decimal.Decimal    `json:"amount"`
	Summary     *string            `json:"summary"`
	ChargedAt   pgtype.Timestamptz `json:"charged_at"`
	ChargedTxID pgtype.UUID        `json:"charged_tx_id"`
}

// 新增挂账（消费后没付款）
func (q *Queries) CreateCredit(ctx context.Context, arg CreateCreditParams) (MemberCredit, error) {
	row := q.db.QueryRow(ctx, createCredit,
		arg.TenantID,
		arg.MemberID,
		arg.Amount,
		arg.Summary,
		arg.ChargedAt,
		arg.ChargedTxID,
	)
	var i MemberCredit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.Amount,
		&i.Summary,
		&i.ChargedAt,
		&i.ChargedTxID,
		&i.SettledAt,
		&i.SettlementTxID,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredit = `-- name: DeleteCredit :exec
DELETE FROM member_credits WHERE id = $1 AND settled_at IS NULL
`

// 撤销错误录入的挂账（仅未清的可以直接删）
func (q *Queries) DeleteCredit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredit, id)
	return err
}

const getCreditByID = `-- name: GetCreditByID :one
SELECT id, tenant_id, member_id, amount, summary, charged_at, charged_tx_id, settled_at, settlement_tx_id, legacy_id, created_at, updated_at FROM member_credits WHERE id = $1
`

func (q *Queries) GetCreditByID(ctx context.Context, id uuid.UUID) (MemberCredit, error) {
	row := q.db.QueryRow(ctx, getCreditByID, id)
	var i MemberCredit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.Amount,
		&i.Summary,
		&i.ChargedAt,
		&i.ChargedTxID,
		&i.SettledAt,
		&i.SettlementTxID,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreditsByChargedTx = `-- name: ListCreditsByChargedTx :many
SELECT id, tenant_id, member_id, amount, summary, charged_at, charged_tx_id, settled_at, settlement_tx_id, legacy_id, created_at, updated_at FROM member_credits
WHERE charged_tx_id = $1
`

// 撤销消费交易时，查这笔交易产生的挂账（未清的删除，已清的阻止撤单）
func (q *Queries) ListCreditsByChargedTx(ctx context.Context, chargedTxID pgtype.UUID) ([]MemberCredit, error) {
	rows, err := q.db.Query(ctx, listCreditsByChargedTx, chargedTxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberCredit
	for rows.Next() {
		var i MemberCredit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemberID,
			&i.Amount,
			&i.Summary,
			&i.ChargedAt,
			&i.ChargedTxID,
			&i.SettledAt,
			&i.SettlementTxID,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditsBySettlementTx = `-- name: ListCreditsBySettlementTx :many
SELECT id, tenant_id, member_id, amount, summary, charged_at, charged_tx_id, settled_at, settlement_tx_id, legacy_id, created_at, updated_at FROM member_credits
WHERE settlement_tx_id = $1
`

// 撤销清账交易时，查哪些挂账被这笔清账清掉（用于恢复）
func (q *Queries) ListCreditsBySettlementTx(ctx context.Context, settlementTxID pgtype.UUID) ([]MemberCredit, error) {
	rows, err := q.db.Query(ctx, listCreditsBySettlementTx, settlementTxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberCredit
	for rows.Next() {
		var i MemberCredit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemberID,
			&i.Amount,
			&i.Summary,
			&i.ChargedAt,
			&i.ChargedTxID,
			&i.SettledAt,
			&i.SettlementTxID,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCreditsByMember = `-- name: ListPendingCreditsByMember :many
SELECT id, tenant_id, member_id, amount, summary, charged_at, charged_tx_id, settled_at, settlement_tx_id, legacy_id, created_at, updated_at FROM member_credits
WHERE member_id = $1 AND settled_at IS NULL
ORDER BY charged_at DESC
`

// 未清挂账
func (q *Queries) ListPendingCreditsByMember(ctx context.Context, memberID uuid.UUID) ([]MemberCredit, error) {
	rows, err := q.db.Query(ctx, listPendingCreditsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberCredit
	for rows.Next() {
		var i MemberCredit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemberID,
			&i.Amount,
			&i.Summary,
			&i.ChargedAt,
			&i.ChargedTxID,
			&i.SettledAt,
			&i.SettlementTxID,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCreditForUpdate = `-- name: LockCreditForUpdate :one
SELECT id, tenant_id, member_id, amount, summary, charged_at, charged_tx_id, settled_at, settlement_tx_id, legacy_id, created_at, updated_at FROM member_credits WHERE id = $1 FOR UPDATE
`

// 单笔清账路径：防双击重复创建 settlement 交易
func (q *Queries) LockCreditForUpdate(ctx context.Context, id uuid.UUID) (MemberCredit, error) {
	row := q.db.QueryRow(ctx, lockCreditForUpdate, id)
	var i MemberCredit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.Amount,
		&i.Summary,
		&i.ChargedAt,
		&i.ChargedTxID,
		&i.SettledAt,
		&i.SettlementTxID,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPendingCreditsByMember = `-- name: LockPendingCreditsByMember :many
SELECT id, tenant_id, member_id, amount, summary, charged_at, charged_tx_id, settled_at, settlement_tx_id, legacy_id, created_at, updated_at FROM member_credits
WHERE member_id = $1 AND settled_at IS NULL
ORDER BY charged_at DESC
FOR UPDATE
`

// 批量清账路径：一次锁定该会员所有未清挂账；再有并发请求会阻塞到本 tx commit
func (q *Queries) LockPendingCreditsByMember(ctx context.Context, memberID uuid.UUID) ([]MemberCredit, error) {
	rows, err := q.db.Query(ctx, lockPendingCreditsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberCredit
	for rows.Next() {
		var i MemberCredit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemberID,
			&i.Amount,
			&i.Summary,
			&i.ChargedAt,
			&i.ChargedTxID,
			&i.SettledAt,
			&i.SettlementTxID,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCreditSettled = `-- name: MarkCreditSettled :one
UPDATE member_credits
SET settled_at       = $2,
    settlement_tx_id = $3,
    updated_at       = now()
WHERE id = $1 AND settled_at IS NULL
RETURNING id, tenant_id, member_id, amount, summary, charged_at, charged_tx_id, settled_at, settlement_tx_id, legacy_id, created_at, updated_at
`

type MarkCreditSettledParams struct {
	ID             uuid.UUID          `json:"id"`
	SettledAt      pgtype.Timestamptz `json:"settled_at"`
	SettlementTxID pgtype.UUID        `json:"settlement_tx_id"`
}

// 标记单笔挂账已清（由 handler 先建 credit_settlement 交易，再调此函数）
func (q *Queries) MarkCreditSettled(ctx context.Context, arg MarkCreditSettledParams) (MemberCredit, error) {
	row := q.db.QueryRow(ctx, markCreditSettled, arg.ID, arg.SettledAt, arg.SettlementTxID)
	var i MemberCredit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemberID,
		&i.Amount,
		&i.Summary,
		&i.ChargedAt,
		&i.ChargedTxID,
		&i.SettledAt,
		&i.SettlementTxID,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCreditsSettledByIDs = `-- name: MarkCreditsSettledByIDs :exec
UPDATE member_credits
SET settled_at       = $1,
    settlement_tx_id = $2,
    updated_at       = now()
WHERE id = ANY($3::uuid[]) AND settled_at IS NULL
`

type MarkCreditsSettledByIDsParams struct {
	SettledAt      pgtype.Timestamptz `json:"settled_at"`
	SettlementTxID pgtype.UUID        `json:"settlement_tx_id"`
	Ids            []uuid.UUID        `json:"ids"`
}

// 批量清挂账：只更新调用方已 FOR UPDATE 锁定的那批 id。
// 不能按 member_id+settled_at 谓词全量更新：READ COMMITTED 下锁定与
// 更新之间并发插入的新挂账会被一并标记已清，金额却不在结算总额里
func (q *Queries) MarkCreditsSettledByIDs(ctx context.Context, arg MarkCreditsSettledByIDsParams) error {
	_, err := q.db.Exec(ctx, markCreditsSettledByIDs, arg.SettledAt, arg.SettlementTxID, arg.Ids)
	return err
}

const sumUnsettledByMember = `-- name: SumUnsettledByMember :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total_unsettled
FROM member_credits
WHERE member_id = $1 AND settled_at IS NULL
`

func (q *Queries) SumUnsettledByMember(ctx context.Context, memberID uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumUnsettledByMember, memberID)
	var total_unsettled decimal.Decimal
	err := row.Scan(&total_unsettled)
	return total_unsettled, err
}

const unsettleCredit = `-- name: UnsettleCredit :exec
UPDATE member_credits
SET settled_at       = NULL,
    settlement_tx_id = NULL,
    updated_at       = now()
WHERE id = $1
`

// 撤销挂账清账：把 settled_at / settlement_tx_id 重置回 NULL
func (q *Queries) UnsettleCredit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsettleCredit, id)
	return err
}
