// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM members
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL
       OR name  ILIKE '%' || $2::text || '%'
       OR phone LIKE  '%' || $2::text || '%')
`

type CountMembersParams struct {
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) CountMembers(ctx context.Context, arg CountMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (tenant_id, name, phone, gender, birthday, notes)
VALUES ($1, $2, $3, COALESCE($6::text, 'unknown'), $4, $5)
RETURNING id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at, legacy_id
`

type CreateMemberParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     string      `json:"name"`
	Phone    *string     `json:"phone"`
	Birthday pgtype.Date `json:"birthday"`
	Notes    *string     `json:"notes"`
	Gender   *string     `json:"gender"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.TenantID,
		arg.Name,
		arg.Phone,
		arg.Birthday,
		arg.Notes,
		arg.Gender,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegacyID,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at, legacy_id FROM members WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegacyID,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT
  m.id, m.tenant_id, m.name, m.phone, m.gender, m.birthday, m.notes, m.status,
  m.created_at, m.updated_at, m.legacy_id,
  COALESCE(cb.total_balance, 0)::numeric AS total_balance,
  COALESCE(pc.total_pending, 0)::numeric AS total_pending,
  COALESCE(cb.card_count, 0)::bigint     AS card_count
FROM members m
LEFT JOIN (
  SELECT member_id, SUM(balance)::numeric AS total_balance, COUNT(*)::bigint AS card_count
  FROM cards WHERE status = 'active' GROUP BY member_id
) cb ON cb.member_id = m.id
LEFT JOIN (
  SELECT member_id, SUM(amount)::numeric AS total_pending
  FROM member_credits WHERE settled_at IS NULL GROUP BY member_id
) pc ON pc.member_id = m.id
WHERE ($3::text IS NULL OR m.status = $3::text)
  AND ($4::text IS NULL
       OR m.name  ILIKE '%' || $4::text || '%'
       OR m.phone LIKE  '%' || $4::text || '%')
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type ListMembersParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
	Search *string `json:"search"`
}

type ListMembersRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Name         string             `json:"name"`
	Phone        *string            `json:"phone"`
	Gender       string             `json:"gender"`
	Birthday     pgtype.Date        `json:"birthday"`
	Notes        *string            `json:"notes"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LegacyID     *string            `json:"legacy_id"`
	TotalBalance decimal.Decimal    `json:"total_balance"`
	TotalPending decimal.Decimal    `json:"total_pending"`
	CardCount    int64              `json:"card_count"`
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Phone,
			&i.Gender,
			&i.Birthday,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LegacyID,
			&i.TotalBalance,
			&i.TotalPending,
			&i.CardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET name       = COALESCE($2::text,    name),
    phone      = COALESCE($3::text,   phone),
    gender     = COALESCE($4::text,  gender),
    birthday   = COALESCE($5::date, birthday),
    notes      = COALESCE($6::text,   notes),
    status     = COALESCE($7::text,  status),
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at, legacy_id
`

type UpdateMemberParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     *string     `json:"name"`
	Phone    *string     `json:"phone"`
	Gender   *string     `json:"gender"`
	Birthday pgtype.Date `json:"birthday"`
	Notes    *string     `json:"notes"`
	Status   *string     `json:"status"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Gender,
		arg.Birthday,
		arg.Notes,
		arg.Status,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegacyID,
	)
	return i, err
}
