// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM members
WHERE status = COALESCE($1::text, status)
`

func (q *Queries) CountMembers(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (tenant_id, name, phone, gender, birthday, notes)
VALUES ($1, $2, $3, COALESCE($6::text, 'unknown'), $4, $5)
RETURNING id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at
`

type CreateMemberParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     string      `json:"name"`
	Phone    *string     `json:"phone"`
	Birthday pgtype.Date `json:"birthday"`
	Notes    *string     `json:"notes"`
	Gender   *string     `json:"gender"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.TenantID,
		arg.Name,
		arg.Phone,
		arg.Birthday,
		arg.Notes,
		arg.Gender,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at FROM members WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at FROM members
WHERE status = COALESCE($3::text, status)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMembersParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Phone,
			&i.Gender,
			&i.Birthday,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET name       = COALESCE($2::text,    name),
    phone      = COALESCE($3::text,   phone),
    gender     = COALESCE($4::text,  gender),
    birthday   = COALESCE($5::date, birthday),
    notes      = COALESCE($6::text,   notes),
    status     = COALESCE($7::text,  status),
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, phone, gender, birthday, notes, status, created_at, updated_at
`

type UpdateMemberParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     *string     `json:"name"`
	Phone    *string     `json:"phone"`
	Gender   *string     `json:"gender"`
	Birthday pgtype.Date `json:"birthday"`
	Notes    *string     `json:"notes"`
	Status   *string     `json:"status"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Gender,
		arg.Birthday,
		arg.Notes,
		arg.Status,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Gender,
		&i.Birthday,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
