// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AuditLog struct {
	ID         int64              `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorType  string             `json:"actor_type"`
	Action     string             `json:"action"`
	TargetType *string            `json:"target_type"`
	TargetID   *string            `json:"target_id"`
	Payload    []byte             `json:"payload"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  *string            `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Edition struct {
	ID           int16               `json:"id"`
	Code         string              `json:"code"`
	Name         string              `json:"name"`
	PriceMonthly decimal.NullDecimal `json:"price_monthly"`
	PriceYearly  decimal.NullDecimal `json:"price_yearly"`
	// {"max_members":100, "max_staff":2, "max_branches":1, "push_monthly":100}, -1=unlimited
	Quotas []byte `json:"quotas"`
	// feature flag 开关集
	Features  []byte             `json:"features"`
	SortOrder int16              `json:"sort_order"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Member struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Name      string             `json:"name"`
	Phone     *string            `json:"phone"`
	Gender    string             `json:"gender"`
	Birthday  pgtype.Date        `json:"birthday"`
	Notes     *string            `json:"notes"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	EditionID          int16              `json:"edition_id"`
	Status             string             `json:"status"`
	BillingCycle       string             `json:"billing_cycle"`
	Source             string             `json:"source"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	CancelAt           pgtype.Timestamptz `json:"cancel_at"`
	AutoRenew          bool               `json:"auto_renew"`
	Notes              *string            `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID uuid.UUID `json:"id"`
	// 子域名前缀，如 demo → demo.<app_domain>
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Email        string             `json:"email"`
	Phone        *string            `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
