// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestAnnouncementVersion = `-- name: GetLatestAnnouncementVersion :one
SELECT a.version, (r.read_at IS NOT NULL)::boolean AS is_read
FROM system_announcements a
LEFT JOIN system_announcement_reads r
  ON r.announcement_id = a.id AND r.user_id = $1
ORDER BY a.published_at DESC
LIMIT 1
`

type GetLatestAnnouncementVersionRow struct {
	Version string `json:"version"`
	IsRead  bool   `json:"is_read"`
}

// 侧边栏版本号红点：最新公告版本；若当前用户未读则前端显红点
func (q *Queries) GetLatestAnnouncementVersion(ctx context.Context, userID uuid.UUID) (GetLatestAnnouncementVersionRow, error) {
	row := q.db.QueryRow(ctx, getLatestAnnouncementVersion, userID)
	var i GetLatestAnnouncementVersionRow
	err := row.Scan(&i.Version, &i.IsRead)
	return i, err
}

const listAllAnnouncementsWithReadStatus = `-- name: ListAllAnnouncementsWithReadStatus :many
SELECT
  a.id, a.version, a.type, a.title, a.summary, a.body_markdown, a.published_at, a.created_at,
  (r.read_at IS NOT NULL)::boolean AS is_read
FROM system_announcements a
LEFT JOIN system_announcement_reads r
  ON r.announcement_id = a.id AND r.user_id = $1
ORDER BY a.published_at DESC
`

type ListAllAnnouncementsWithReadStatusRow struct {
	ID           uuid.UUID          `json:"id"`
	Version      string             `json:"version"`
	Type         string             `json:"type"`
	Title        string             `json:"title"`
	Summary      string             `json:"summary"`
	BodyMarkdown string             `json:"body_markdown"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsRead       bool               `json:"is_read"`
}

// changelog 页使用：所有公告 + 当前 user 的已读状态
func (q *Queries) ListAllAnnouncementsWithReadStatus(ctx context.Context, userID uuid.UUID) ([]ListAllAnnouncementsWithReadStatusRow, error) {
	rows, err := q.db.Query(ctx, listAllAnnouncementsWithReadStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllAnnouncementsWithReadStatusRow
	for rows.Next() {
		var i ListAllAnnouncementsWithReadStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.BodyMarkdown,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadAnnouncementsForUser = `-- name: ListUnreadAnnouncementsForUser :many
SELECT a.id, a.version, a.type, a.title, a.summary, a.body_markdown, a.published_at, a.created_at
FROM system_announcements a
WHERE NOT EXISTS (
  SELECT 1 FROM system_announcement_reads r
  WHERE r.announcement_id = a.id AND r.user_id = $1
)
ORDER BY a.published_at DESC
`

// 某用户未读的系统公告（铃铛通知合并用）
func (q *Queries) ListUnreadAnnouncementsForUser(ctx context.Context, userID uuid.UUID) ([]SystemAnnouncement, error) {
	rows, err := q.db.Query(ctx, listUnreadAnnouncementsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemAnnouncement
	for rows.Next() {
		var i SystemAnnouncement
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.BodyMarkdown,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAnnouncementsRead = `-- name: MarkAllAnnouncementsRead :exec
INSERT INTO system_announcement_reads (user_id, announcement_id)
SELECT $1, id FROM system_announcements
ON CONFLICT DO NOTHING
`

func (q *Queries) MarkAllAnnouncementsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllAnnouncementsRead, userID)
	return err
}

const markAnnouncementReadByVersion = `-- name: MarkAnnouncementReadByVersion :exec
INSERT INTO system_announcement_reads (user_id, announcement_id)
SELECT $1, id FROM system_announcements WHERE version = $2
ON CONFLICT DO NOTHING
`

type MarkAnnouncementReadByVersionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Version string    `json:"version"`
}

// 按 version 字符串标记已读（前端传 version 更稳定，不用暴露内部 UUID）
func (q *Queries) MarkAnnouncementReadByVersion(ctx context.Context, arg MarkAnnouncementReadByVersionParams) error {
	_, err := q.db.Exec(ctx, markAnnouncementReadByVersion, arg.UserID, arg.Version)
	return err
}
