// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_methods.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countPaymentMethodUsage = `-- name: CountPaymentMethodUsage :one
SELECT count(*) FROM transactions WHERE payment_method_id = $1
`

// 删除前检查：这个支付方式是否被 transactions 引用
func (q *Queries) CountPaymentMethodUsage(ctx context.Context, paymentMethodID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentMethodUsage, paymentMethodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (tenant_id, name, sort_order, is_active)
VALUES ($1, $2, COALESCE($3::int, 99), TRUE)
RETURNING id, tenant_id, name, sort_order, is_active, legacy_id, created_at, updated_at
`

type CreatePaymentMethodParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	SortOrder *int32    `json:"sort_order"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod, arg.TenantID, arg.Name, arg.SortOrder)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePaymentMethod = `-- name: DeletePaymentMethod :exec
DELETE FROM payment_methods WHERE id = $1
`

func (q *Queries) DeletePaymentMethod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePaymentMethod, id)
	return err
}

const getPaymentMethodByID = `-- name: GetPaymentMethodByID :one
SELECT id, tenant_id, name, sort_order, is_active, legacy_id, created_at, updated_at FROM payment_methods WHERE id = $1
`

func (q *Queries) GetPaymentMethodByID(ctx context.Context, id uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByID, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT id, tenant_id, name, sort_order, is_active, legacy_id, created_at, updated_at FROM payment_methods
WHERE is_active = COALESCE($1::bool, is_active)
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListPaymentMethods(ctx context.Context, isActive *bool) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE payment_methods
SET name       = COALESCE($2::text,       name),
    sort_order = COALESCE($3::int,  sort_order),
    is_active  = COALESCE($4::bool,  is_active),
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, sort_order, is_active, legacy_id, created_at, updated_at
`

type UpdatePaymentMethodParams struct {
	ID        uuid.UUID `json:"id"`
	Name      *string   `json:"name"`
	SortOrder *int32    `json:"sort_order"`
	IsActive  *bool     `json:"is_active"`
}

func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethod,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
