// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const reportBirthdayReminders = `-- name: ReportBirthdayReminders :many
SELECT id, name, phone, birthday
FROM members
WHERE status = 'active'
  AND birthday IS NOT NULL
  AND to_char(birthday, 'MM-DD') IN (
    SELECT to_char(CURRENT_DATE + (gs || ' days')::interval, 'MM-DD')
    FROM generate_series(0, 15) AS gs
  )
ORDER BY to_char(birthday, 'MM-DD')
`

type ReportBirthdayRemindersRow struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Phone    *string     `json:"phone"`
	Birthday pgtype.Date `json:"birthday"`
}

// 未来 15 天内生日（不看年份，按月日）
func (q *Queries) ReportBirthdayReminders(ctx context.Context) ([]ReportBirthdayRemindersRow, error) {
	rows, err := q.db.Query(ctx, reportBirthdayReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportBirthdayRemindersRow
	for rows.Next() {
		var i ReportBirthdayRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Birthday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportBusiness = `-- name: ReportBusiness :one
SELECT
  COALESCE(SUM(CASE WHEN kind='sale'     AND status='completed' THEN actual_paid_amount ELSE 0 END), 0)::numeric AS sale_revenue,
  COALESCE(SUM(CASE WHEN kind='recharge' AND status='completed' THEN actual_paid_amount ELSE 0 END), 0)::numeric AS recharge_amount,
  COALESCE(SUM(CASE WHEN kind='sale' AND status='completed'
    AND EXISTS (SELECT 1 FROM card_balance_logs l
                WHERE l.transaction_id = transactions.id AND l.change_type = 'consume')
    THEN actual_paid_amount ELSE 0 END), 0)::numeric AS card_consumption,
  COUNT(DISTINCT CASE WHEN kind='sale' AND status='completed' THEN COALESCE(member_id::text, id::text) END)::bigint AS customer_count
FROM transactions
WHERE transaction_time >= $1 AND transaction_time < $2
`

type ReportBusinessParams struct {
	TransactionTime   pgtype.Timestamptz `json:"transaction_time"`
	TransactionTime_2 pgtype.Timestamptz `json:"transaction_time_2"`
}

type ReportBusinessRow struct {
	SaleRevenue     decimal.Decimal `json:"sale_revenue"`
	RechargeAmount  decimal.Decimal `json:"recharge_amount"`
	CardConsumption decimal.Decimal `json:"card_consumption"`
	CustomerCount   int64           `json:"customer_count"`
}

// 营业报表：区间内的综合统计（对齐老系统口径）
//
//	sale_revenue     : kind='sale' 实收合计（含挂账场景）
//	credit_charged   : 区间内新增的挂账金额（老口径"挂账也算营业"）
//	card_consumption : sale 中走会员卡部分（按扣卡流水判定：多卡支付时
//	                   transactions.card_id 为 NULL，不能按 card_id 判）
//	recharge_amount  : kind='recharge' 实收合计（办卡/充值）
//	customer_count   : 客数（有 member_id 按会员去重；无 member_id 按 tx id 去重）
func (q *Queries) ReportBusiness(ctx context.Context, arg ReportBusinessParams) (ReportBusinessRow, error) {
	row := q.db.QueryRow(ctx, reportBusiness, arg.TransactionTime, arg.TransactionTime_2)
	var i ReportBusinessRow
	err := row.Scan(
		&i.SaleRevenue,
		&i.RechargeAmount,
		&i.CardConsumption,
		&i.CustomerCount,
	)
	return i, err
}

const reportCardPool = `-- name: ReportCardPool :one
SELECT COALESCE(SUM(balance), 0)::numeric AS total
FROM cards WHERE status = 'active'
`

// 卡池余额：当前店内所有 active 卡的余额总和
// 用于首页 KPI；RLS 自动按 tenant 隔离
func (q *Queries) ReportCardPool(ctx context.Context) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, reportCardPool)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const reportCardSalesSummary = `-- name: ReportCardSalesSummary :many
SELECT
  (CASE
    WHEN c.final_price <> ct.price OR c.final_discount_rate <> ct.discount_rate
      THEN '00000000-0000-0000-0000-000000000000'::uuid
    ELSE ct.id
  END)::uuid AS card_type_id,
  (CASE
    WHEN c.final_price <> ct.price OR c.final_discount_rate <> ct.discount_rate
      THEN '自定义面值卡'
    ELSE ct.name
  END)::text AS card_type_name,
  COUNT(c.id)::bigint         AS card_count,
  SUM(c.final_price)::numeric AS total
FROM cards c
JOIN card_types ct ON ct.id = c.card_type_id
WHERE c.issued_at >= $1 AND c.issued_at < $2
  -- 排除办卡交易已撤销的卡（卡已冻结清零，不应计入销售）
  AND NOT EXISTS (
    SELECT 1 FROM transactions t
    WHERE t.card_id = c.id AND t.kind = 'recharge' AND t.status = 'voided'
  )
GROUP BY 1, 2
ORDER BY total DESC
`

type ReportCardSalesSummaryParams struct {
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	IssuedAt_2 pgtype.Timestamptz `json:"issued_at_2"`
}

type ReportCardSalesSummaryRow struct {
	CardTypeID   uuid.UUID       `json:"card_type_id"`
	CardTypeName string          `json:"card_type_name"`
	CardCount    int64           `json:"card_count"`
	Total        decimal.Decimal `json:"total"`
}

// 自定义面值卡（final_price/折扣率偏离模板）聚为一行"自定义面值卡"，id 返回哨兵零 UUID；
// 其余按卡型分组。
func (q *Queries) ReportCardSalesSummary(ctx context.Context, arg ReportCardSalesSummaryParams) ([]ReportCardSalesSummaryRow, error) {
	rows, err := q.db.Query(ctx, reportCardSalesSummary, arg.IssuedAt, arg.IssuedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportCardSalesSummaryRow
	for rows.Next() {
		var i ReportCardSalesSummaryRow
		if err := rows.Scan(
			&i.CardTypeID,
			&i.CardTypeName,
			&i.CardCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCreditsCharged = `-- name: ReportCreditsCharged :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM member_credits
WHERE charged_at >= $1 AND charged_at < $2
`

type ReportCreditsChargedParams struct {
	ChargedAt   pgtype.Timestamptz `json:"charged_at"`
	ChargedAt_2 pgtype.Timestamptz `json:"charged_at_2"`
}

// 区间内新增的挂账（营业报表要加上）
func (q *Queries) ReportCreditsCharged(ctx context.Context, arg ReportCreditsChargedParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, reportCreditsCharged, arg.ChargedAt, arg.ChargedAt_2)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const reportMemberRanking = `-- name: ReportMemberRanking :many
SELECT
  m.id, m.name, m.phone,
  SUM(t.actual_paid_amount)::numeric AS total_consumption
FROM transactions t
JOIN members m ON m.id = t.member_id
WHERE t.kind = 'sale'
  AND t.status = 'completed'
  AND t.transaction_time >= $1
  AND t.transaction_time <  $2
GROUP BY m.id, m.name, m.phone
ORDER BY total_consumption DESC
LIMIT $3 OFFSET $4
`

type ReportMemberRankingParams struct {
	TransactionTime   pgtype.Timestamptz `json:"transaction_time"`
	TransactionTime_2 pgtype.Timestamptz `json:"transaction_time_2"`
	Limit             int32              `json:"limit"`
	Offset            int32              `json:"offset"`
}

type ReportMemberRankingRow struct {
	ID               uuid.UUID       `json:"id"`
	Name             string          `json:"name"`
	Phone            *string         `json:"phone"`
	TotalConsumption decimal.Decimal `json:"total_consumption"`
}

func (q *Queries) ReportMemberRanking(ctx context.Context, arg ReportMemberRankingParams) ([]ReportMemberRankingRow, error) {
	rows, err := q.db.Query(ctx, reportMemberRanking,
		arg.TransactionTime,
		arg.TransactionTime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportMemberRankingRow
	for rows.Next() {
		var i ReportMemberRankingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.TotalConsumption,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportMonthlyBusiness = `-- name: ReportMonthlyBusiness :many
WITH months AS (
  SELECT ($1::timestamptz - make_interval(months => g))     AS m_start,
         ($1::timestamptz - make_interval(months => g - 1)) AS m_end
  FROM generate_series(0, 11) AS g
)
SELECT
  m.m_start::timestamptz AS m_start,
  (COALESCE((SELECT sum(t.actual_paid_amount) FROM transactions t
             WHERE t.status = 'completed' AND t.kind = 'sale'
               AND t.transaction_time >= m.m_start AND t.transaction_time < m.m_end), 0)
   + COALESCE((SELECT sum(mc.amount) FROM member_credits mc
               WHERE mc.charged_at >= m.m_start AND mc.charged_at < m.m_end), 0))::numeric(12,2) AS revenue,
  COALESCE((SELECT sum(mc.amount) FROM member_credits mc
            WHERE mc.charged_at >= m.m_start AND mc.charged_at < m.m_end), 0)::numeric(12,2) AS pending_added,
  COALESCE((SELECT sum(mc.amount) FROM member_credits mc
            WHERE mc.settled_at >= m.m_start AND mc.settled_at < m.m_end), 0)::numeric(12,2) AS pending_cleared,
  COALESCE((SELECT sum(t.actual_paid_amount) FROM transactions t
            WHERE t.status = 'completed' AND t.kind = 'recharge'
              AND t.transaction_time >= m.m_start AND t.transaction_time < m.m_end), 0)::numeric(12,2) AS recharge,
  COALESCE((SELECT sum(-l.delta) FROM card_balance_logs l
            JOIN transactions t2 ON t2.id = l.transaction_id
            WHERE l.change_type = 'consume' AND t2.status = 'completed'
              AND t2.kind IN ('sale', 'credit_settlement')
              AND t2.transaction_time >= m.m_start AND t2.transaction_time < m.m_end), 0)::numeric(12,2) AS card_consumption,
  COALESCE((SELECT count(DISTINCT COALESCE(t.member_id::text, t.id::text)) FROM transactions t
            WHERE t.status = 'completed' AND t.kind = 'sale'
              AND t.transaction_time >= m.m_start AND t.transaction_time < m.m_end), 0)::int AS customers,
  COALESCE((SELECT count(*) FROM members mm
            WHERE mm.created_at >= m.m_start AND mm.created_at < m.m_end), 0)::int AS new_members
FROM months m
ORDER BY m.m_start
`

type ReportMonthlyBusinessRow struct {
	MStart          pgtype.Timestamptz `json:"m_start"`
	Revenue         decimal.Decimal    `json:"revenue"`
	PendingAdded    decimal.Decimal    `json:"pending_added"`
	PendingCleared  decimal.Decimal    `json:"pending_cleared"`
	Recharge        decimal.Decimal    `json:"recharge"`
	CardConsumption decimal.Decimal    `json:"card_consumption"`
	Customers       int32              `json:"customers"`
	NewMembers      int32              `json:"new_members"`
}

// 月度对比：近 12 个月各项经营指标（老系统「月度对比」等价口径）
//
//	revenue          营业额 = sale 实收 + 当月新增挂账（挂账登记行实收为 0，金额在挂账表）
//	card_consumption 卡耗 = 扣卡流水净额（消费+清账，撤销的不计）
//	customers        客数 = sale 按会员去重（非会员按交易），含挂账登记，不含清账/办卡
//
// base 由调用方传入「本月首日的本地 0 点」，月界在 timestamptz 域上前推
func (q *Queries) ReportMonthlyBusiness(ctx context.Context, base pgtype.Timestamptz) ([]ReportMonthlyBusinessRow, error) {
	rows, err := q.db.Query(ctx, reportMonthlyBusiness, base)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportMonthlyBusinessRow
	for rows.Next() {
		var i ReportMonthlyBusinessRow
		if err := rows.Scan(
			&i.MStart,
			&i.Revenue,
			&i.PendingAdded,
			&i.PendingCleared,
			&i.Recharge,
			&i.CardConsumption,
			&i.Customers,
			&i.NewMembers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPaymentSummary = `-- name: ReportPaymentSummary :many
SELECT
  pm.id   AS payment_method_id,
  pm.name AS payment_method_name,
  COUNT(t.id)::bigint              AS tx_count,
  SUM(t.actual_paid_amount)::numeric AS total
FROM transactions t
JOIN payment_methods pm ON pm.id = t.payment_method_id
WHERE t.status = 'completed'
  AND t.transaction_time >= $1
  AND t.transaction_time <  $2
GROUP BY pm.id, pm.name
ORDER BY total DESC
`

type ReportPaymentSummaryParams struct {
	TransactionTime   pgtype.Timestamptz `json:"transaction_time"`
	TransactionTime_2 pgtype.Timestamptz `json:"transaction_time_2"`
}

type ReportPaymentSummaryRow struct {
	PaymentMethodID   uuid.UUID       `json:"payment_method_id"`
	PaymentMethodName string          `json:"payment_method_name"`
	TxCount           int64           `json:"tx_count"`
	Total             decimal.Decimal `json:"total"`
}

func (q *Queries) ReportPaymentSummary(ctx context.Context, arg ReportPaymentSummaryParams) ([]ReportPaymentSummaryRow, error) {
	rows, err := q.db.Query(ctx, reportPaymentSummary, arg.TransactionTime, arg.TransactionTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportPaymentSummaryRow
	for rows.Next() {
		var i ReportPaymentSummaryRow
		if err := rows.Scan(
			&i.PaymentMethodID,
			&i.PaymentMethodName,
			&i.TxCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPendingByMember = `-- name: ReportPendingByMember :many
SELECT
  m.id, m.name, m.phone,
  COUNT(mc.id)::bigint         AS record_count,
  SUM(mc.amount)::numeric       AS total_pending,
  MIN(mc.charged_at)            AS earliest,
  MAX(mc.charged_at)            AS latest
FROM member_credits mc
JOIN members m ON m.id = mc.member_id
WHERE mc.settled_at IS NULL
GROUP BY m.id, m.name, m.phone
ORDER BY total_pending DESC
LIMIT $1 OFFSET $2
`

type ReportPendingByMemberParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ReportPendingByMemberRow struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	Phone        *string         `json:"phone"`
	RecordCount  int64           `json:"record_count"`
	TotalPending decimal.Decimal `json:"total_pending"`
	Earliest     interface{}     `json:"earliest"`
	Latest       interface{}     `json:"latest"`
}

func (q *Queries) ReportPendingByMember(ctx context.Context, arg ReportPendingByMemberParams) ([]ReportPendingByMemberRow, error) {
	rows, err := q.db.Query(ctx, reportPendingByMember, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportPendingByMemberRow
	for rows.Next() {
		var i ReportPendingByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.RecordCount,
			&i.TotalPending,
			&i.Earliest,
			&i.Latest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPendingStats = `-- name: ReportPendingStats :one
SELECT
  COUNT(*)::bigint              AS record_count,
  COUNT(DISTINCT member_id)::bigint AS member_count,
  COALESCE(SUM(amount), 0)::numeric AS total_amount
FROM member_credits
WHERE settled_at IS NULL
`

type ReportPendingStatsRow struct {
	RecordCount int64           `json:"record_count"`
	MemberCount int64           `json:"member_count"`
	TotalAmount decimal.Decimal `json:"total_amount"`
}

func (q *Queries) ReportPendingStats(ctx context.Context) (ReportPendingStatsRow, error) {
	row := q.db.QueryRow(ctx, reportPendingStats)
	var i ReportPendingStatsRow
	err := row.Scan(&i.RecordCount, &i.MemberCount, &i.TotalAmount)
	return i, err
}

const reportServiceRanking = `-- name: ReportServiceRanking :many
SELECT
  s.id           AS service_id,
  s.name         AS service_name,
  SUM(ti.price * ti.quantity)::numeric AS total_sales,
  SUM(ti.quantity)::bigint              AS total_count
FROM transaction_items ti
JOIN services     s ON s.id = ti.service_id
JOIN transactions t ON t.id = ti.transaction_id
WHERE t.status = 'completed'
  AND t.kind = 'sale'
  AND t.transaction_time >= $1
  AND t.transaction_time <  $2
GROUP BY s.id, s.name
ORDER BY total_sales DESC
LIMIT $3 OFFSET $4
`

type ReportServiceRankingParams struct {
	TransactionTime   pgtype.Timestamptz `json:"transaction_time"`
	TransactionTime_2 pgtype.Timestamptz `json:"transaction_time_2"`
	Limit             int32              `json:"limit"`
	Offset            int32              `json:"offset"`
}

type ReportServiceRankingRow struct {
	ServiceID   uuid.UUID       `json:"service_id"`
	ServiceName string          `json:"service_name"`
	TotalSales  decimal.Decimal `json:"total_sales"`
	TotalCount  int64           `json:"total_count"`
}

func (q *Queries) ReportServiceRanking(ctx context.Context, arg ReportServiceRankingParams) ([]ReportServiceRankingRow, error) {
	rows, err := q.db.Query(ctx, reportServiceRanking,
		arg.TransactionTime,
		arg.TransactionTime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportServiceRankingRow
	for rows.Next() {
		var i ReportServiceRankingRow
		if err := rows.Scan(
			&i.ServiceID,
			&i.ServiceName,
			&i.TotalSales,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSleepingMembers = `-- name: ReportSleepingMembers :many
SELECT
  m.id, m.name, m.phone, m.created_at,
  MAX(t.transaction_time) AS last_visit
FROM members m
LEFT JOIN transactions t
  ON t.member_id = m.id AND t.kind = 'sale' AND t.status = 'completed'
WHERE m.status = 'active'
GROUP BY m.id, m.name, m.phone, m.created_at
HAVING MAX(t.transaction_time) IS NULL OR MAX(t.transaction_time) < $1
ORDER BY MAX(t.transaction_time) ASC NULLS FIRST
LIMIT $2 OFFSET $3
`

type ReportSleepingMembersParams struct {
	TransactionTime pgtype.Timestamptz `json:"transaction_time"`
	Limit           int32              `json:"limit"`
	Offset          int32              `json:"offset"`
}

type ReportSleepingMembersRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Phone     *string            `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastVisit interface{}        `json:"last_visit"`
}

// 90 天无 sale 交易的活跃会员
func (q *Queries) ReportSleepingMembers(ctx context.Context, arg ReportSleepingMembersParams) ([]ReportSleepingMembersRow, error) {
	rows, err := q.db.Query(ctx, reportSleepingMembers, arg.TransactionTime, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportSleepingMembersRow
	for rows.Next() {
		var i ReportSleepingMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.CreatedAt,
			&i.LastVisit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTodayBirthdays = `-- name: ReportTodayBirthdays :many
SELECT id, name, phone, birthday
FROM members
WHERE status = 'active'
  AND birthday IS NOT NULL
  AND to_char(birthday, 'MM-DD') = to_char(CURRENT_DATE, 'MM-DD')
ORDER BY name
`

type ReportTodayBirthdaysRow struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Phone    *string     `json:"phone"`
	Birthday pgtype.Date `json:"birthday"`
}

// 今日生日：铃铛通知用，比 15 天窗口少拉 14 天数据
func (q *Queries) ReportTodayBirthdays(ctx context.Context) ([]ReportTodayBirthdaysRow, error) {
	rows, err := q.db.Query(ctx, reportTodayBirthdays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportTodayBirthdaysRow
	for rows.Next() {
		var i ReportTodayBirthdaysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Birthday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
