// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countServiceUsage = `-- name: CountServiceUsage :one
SELECT
  (SELECT count(*) FROM transaction_items  ti WHERE ti.service_id = $1)::bigint AS tx_item_count,
  (SELECT count(*) FROM appointment_services aps WHERE aps.service_id = $1)::bigint AS appt_count
`

type CountServiceUsageRow struct {
	TxItemCount int64 `json:"tx_item_count"`
	ApptCount   int64 `json:"appt_count"`
}

// 删除前检查：是否被 transaction_items 或 appointment_services 引用
func (q *Queries) CountServiceUsage(ctx context.Context, serviceID pgtype.UUID) (CountServiceUsageRow, error) {
	row := q.db.QueryRow(ctx, countServiceUsage, serviceID)
	var i CountServiceUsageRow
	err := row.Scan(&i.TxItemCount, &i.ApptCount)
	return i, err
}

const countServices = `-- name: CountServices :one
SELECT count(*) FROM services
`

func (q *Queries) CountServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countServices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
  tenant_id, name, price, duration_min, category, description,
  no_discount, sort_order
)
VALUES (
  $1, $2, $3,
  $4::int,
  $5::text,
  $6::text,
  COALESCE($7::bool, FALSE),
  COALESCE($8::int, 99)
)
RETURNING id, tenant_id, name, price, duration_min, category, description, no_discount, sort_order, status, legacy_id, created_at, updated_at
`

type CreateServiceParams struct {
	TenantID    uuid.UUID       `json:"tenant_id"`
	Name        string          `json:"name"`
	Price       decimal.Decimal `json:"price"`
	DurationMin *int32          `json:"duration_min"`
	Category    *string         `json:"category"`
	Description *string         `json:"description"`
	NoDiscount  *bool           `json:"no_discount"`
	SortOrder   *int32          `json:"sort_order"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.TenantID,
		arg.Name,
		arg.Price,
		arg.DurationMin,
		arg.Category,
		arg.Description,
		arg.NoDiscount,
		arg.SortOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Price,
		&i.DurationMin,
		&i.Category,
		&i.Description,
		&i.NoDiscount,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, tenant_id, name, price, duration_min, category, description, no_discount, sort_order, status, legacy_id, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Price,
		&i.DurationMin,
		&i.Category,
		&i.Description,
		&i.NoDiscount,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, tenant_id, name, price, duration_min, category, description, no_discount, sort_order, status, legacy_id, created_at, updated_at FROM services
WHERE status = COALESCE($1::text, status)
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListServices(ctx context.Context, status *string) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Price,
			&i.DurationMin,
			&i.Category,
			&i.Description,
			&i.NoDiscount,
			&i.SortOrder,
			&i.Status,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name         = COALESCE($2::text,         name),
    price        = COALESCE($3::numeric,     price),
    duration_min = COALESCE($4::int,  duration_min),
    category     = COALESCE($5::text,     category),
    description  = COALESCE($6::text,  description),
    no_discount  = COALESCE($7::bool,  no_discount),
    sort_order   = COALESCE($8::int,    sort_order),
    status       = COALESCE($9::text,       status),
    updated_at   = now()
WHERE id = $1
RETURNING id, tenant_id, name, price, duration_min, category, description, no_discount, sort_order, status, legacy_id, created_at, updated_at
`

type UpdateServiceParams struct {
	ID          uuid.UUID           `json:"id"`
	Name        *string             `json:"name"`
	Price       decimal.NullDecimal `json:"price"`
	DurationMin *int32              `json:"duration_min"`
	Category    *string             `json:"category"`
	Description *string             `json:"description"`
	NoDiscount  *bool               `json:"no_discount"`
	SortOrder   *int32              `json:"sort_order"`
	Status      *string             `json:"status"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.DurationMin,
		arg.Category,
		arg.Description,
		arg.NoDiscount,
		arg.SortOrder,
		arg.Status,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Price,
		&i.DurationMin,
		&i.Category,
		&i.Description,
		&i.NoDiscount,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
