// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (
  tenant_id, name, position, phone, hire_date,
  counts_commission, default_commission_rate, sort_order
)
VALUES (
  $1, $2, $3,
  $4::text,
  $5::date,
  COALESCE($6::bool, TRUE),
  COALESCE($7::numeric, 0.000),
  COALESCE($8::int, 99)
)
RETURNING id, tenant_id, user_id, name, position, phone, hire_date, counts_commission, default_commission_rate, sort_order, status, legacy_id, created_at, updated_at
`

type CreateStaffParams struct {
	TenantID              uuid.UUID           `json:"tenant_id"`
	Name                  string              `json:"name"`
	Position              string              `json:"position"`
	Phone                 *string             `json:"phone"`
	HireDate              pgtype.Date         `json:"hire_date"`
	CountsCommission      *bool               `json:"counts_commission"`
	DefaultCommissionRate decimal.NullDecimal `json:"default_commission_rate"`
	SortOrder             *int32              `json:"sort_order"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.TenantID,
		arg.Name,
		arg.Position,
		arg.Phone,
		arg.HireDate,
		arg.CountsCommission,
		arg.DefaultCommissionRate,
		arg.SortOrder,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Position,
		&i.Phone,
		&i.HireDate,
		&i.CountsCommission,
		&i.DefaultCommissionRate,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaff = `-- name: DeleteStaff :exec
DELETE FROM staff WHERE id = $1
`

func (q *Queries) DeleteStaff(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaff, id)
	return err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, tenant_id, user_id, name, position, phone, hire_date, counts_commission, default_commission_rate, sort_order, status, legacy_id, created_at, updated_at FROM staff WHERE id = $1
`

func (q *Queries) GetStaffByID(ctx context.Context, id uuid.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Position,
		&i.Phone,
		&i.HireDate,
		&i.CountsCommission,
		&i.DefaultCommissionRate,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, tenant_id, user_id, name, position, phone, hire_date, counts_commission, default_commission_rate, sort_order, status, legacy_id, created_at, updated_at FROM staff
WHERE status = COALESCE($1::text, status)
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListStaff(ctx context.Context, status *string) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaff, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.Position,
			&i.Phone,
			&i.HireDate,
			&i.CountsCommission,
			&i.DefaultCommissionRate,
			&i.SortOrder,
			&i.Status,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkStaffFromAppointments = `-- name: UnlinkStaffFromAppointments :exec
UPDATE appointments SET assigned_staff_id = NULL WHERE assigned_staff_id = $1
`

func (q *Queries) UnlinkStaffFromAppointments(ctx context.Context, assignedStaffID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlinkStaffFromAppointments, assignedStaffID)
	return err
}

const unlinkStaffFromTransactions = `-- name: UnlinkStaffFromTransactions :exec
UPDATE transactions SET staff_id = NULL WHERE staff_id = $1
`

func (q *Queries) UnlinkStaffFromTransactions(ctx context.Context, staffID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlinkStaffFromTransactions, staffID)
	return err
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE staff
SET name                    = COALESCE($2::text,      name),
    position                = COALESCE($3::text,  position),
    phone                   = COALESCE($4::text,     phone),
    hire_date               = COALESCE($5::date, hire_date),
    status                  = COALESCE($6::text,    status),
    counts_commission       = COALESCE($7::bool, counts_commission),
    default_commission_rate = COALESCE($8::numeric, default_commission_rate),
    sort_order              = COALESCE($9::int, sort_order),
    updated_at              = now()
WHERE id = $1
RETURNING id, tenant_id, user_id, name, position, phone, hire_date, counts_commission, default_commission_rate, sort_order, status, legacy_id, created_at, updated_at
`

type UpdateStaffParams struct {
	ID                    uuid.UUID           `json:"id"`
	Name                  *string             `json:"name"`
	Position              *string             `json:"position"`
	Phone                 *string             `json:"phone"`
	HireDate              pgtype.Date         `json:"hire_date"`
	Status                *string             `json:"status"`
	CountsCommission      *bool               `json:"counts_commission"`
	DefaultCommissionRate decimal.NullDecimal `json:"default_commission_rate"`
	SortOrder             *int32              `json:"sort_order"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.ID,
		arg.Name,
		arg.Position,
		arg.Phone,
		arg.HireDate,
		arg.Status,
		arg.CountsCommission,
		arg.DefaultCommissionRate,
		arg.SortOrder,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Position,
		&i.Phone,
		&i.HireDate,
		&i.CountsCommission,
		&i.DefaultCommissionRate,
		&i.SortOrder,
		&i.Status,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
