// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"
)

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, status, created_at, updated_at FROM tenants WHERE slug = $1
`

// 供 middleware/tenant.go 解析 X-Tenant-Slug
func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
