// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransactionItem = `-- name: CreateTransactionItem :one
INSERT INTO transaction_items (
  tenant_id, transaction_id, service_id, service_name_snapshot,
  price, quantity, commission_amount
) VALUES (
  $1, $2,
  $6::uuid,
  $3, $4, $5,
  COALESCE($7::numeric, 0)
) RETURNING id, tenant_id, transaction_id, service_id, service_name_snapshot, price, quantity, commission_amount, legacy_id, created_at
`

type CreateTransactionItemParams struct {
	TenantID            uuid.UUID           `json:"tenant_id"`
	TransactionID       uuid.UUID           `json:"transaction_id"`
	ServiceNameSnapshot string              `json:"service_name_snapshot"`
	Price               decimal.Decimal     `json:"price"`
	Quantity            int32               `json:"quantity"`
	ServiceID           pgtype.UUID         `json:"service_id"`
	CommissionAmount    decimal.NullDecimal `json:"commission_amount"`
}

func (q *Queries) CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error) {
	row := q.db.QueryRow(ctx, createTransactionItem,
		arg.TenantID,
		arg.TransactionID,
		arg.ServiceNameSnapshot,
		arg.Price,
		arg.Quantity,
		arg.ServiceID,
		arg.CommissionAmount,
	)
	var i TransactionItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TransactionID,
		&i.ServiceID,
		&i.ServiceNameSnapshot,
		&i.Price,
		&i.Quantity,
		&i.CommissionAmount,
		&i.LegacyID,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionItems = `-- name: ListTransactionItems :many
SELECT id, tenant_id, transaction_id, service_id, service_name_snapshot, price, quantity, commission_amount, legacy_id, created_at FROM transaction_items
WHERE transaction_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTransactionItems(ctx context.Context, transactionID uuid.UUID) ([]TransactionItem, error) {
	rows, err := q.db.Query(ctx, listTransactionItems, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionItem
	for rows.Next() {
		var i TransactionItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TransactionID,
			&i.ServiceID,
			&i.ServiceNameSnapshot,
			&i.Price,
			&i.Quantity,
			&i.CommissionAmount,
			&i.LegacyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
