// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countTransactionsBy = `-- name: CountTransactionsBy :one
SELECT count(*) FROM transactions
WHERE ($1::timestamptz IS NULL OR transaction_time >= $1::timestamptz)
  AND ($2::timestamptz   IS NULL OR transaction_time <  $2::timestamptz)
  AND ($3::text              IS NULL OR kind              =  $3::text)
  AND ($4::uuid         IS NULL OR member_id        =  $4::uuid)
  AND ($5::text IS NULL
       OR EXISTS (SELECT 1 FROM members mm WHERE mm.id = transactions.member_id
                  AND (mm.name ILIKE '%' || $5::text || '%'
                       OR mm.phone ILIKE '%' || $5::text || '%'))
       OR customer_name ILIKE '%' || $5::text || '%'
       OR summary ILIKE '%' || $5::text || '%'
       OR EXISTS (SELECT 1 FROM transaction_items ti2
                  WHERE ti2.transaction_id = transactions.id
                    AND ti2.service_name_snapshot ILIKE '%' || $5::text || '%')
       OR ($5::text ~ '^[0-9]+(\.[0-9]{1,2})?$'
           AND (total_amount = $5::numeric
                OR actual_paid_amount = $5::numeric)))
  AND (
    $6::text IS NOT NULL AND status = $6::text
    OR $6::text IS NULL AND ($7::bool IS TRUE OR status = 'completed')
  )
`

type CountTransactionsByParams struct {
	StartDate     pgtype.Timestamptz `json:"start_date"`
	EndDate       pgtype.Timestamptz `json:"end_date"`
	Kind          *string            `json:"kind"`
	MemberID      pgtype.UUID        `json:"member_id"`
	Search        *string            `json:"search"`
	Status        *string            `json:"status"`
	IncludeVoided *bool              `json:"include_voided"`
}

func (q *Queries) CountTransactionsBy(ctx context.Context, arg CountTransactionsByParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsBy,
		arg.StartDate,
		arg.EndDate,
		arg.Kind,
		arg.MemberID,
		arg.Search,
		arg.Status,
		arg.IncludeVoided,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  tenant_id, kind, status,
  member_id, customer_name, staff_id,
  payment_method_id, card_id,
  total_amount, actual_paid_amount, discount_amount,
  transaction_time, summary, notes
) VALUES (
  $1, $2, 'completed',
  $6::uuid,
  $7::text,
  $8::uuid,
  $3,
  $9::uuid,
  $4, $5,
  COALESCE($10::numeric, 0),
  COALESCE($11::timestamptz, now()),
  $12::text,
  $13::text
) RETURNING id, tenant_id, kind, status, member_id, customer_name, staff_id, payment_method_id, card_id, total_amount, actual_paid_amount, discount_amount, transaction_time, voided_at, voided_by_user_id, voided_by_name, void_reason, summary, notes, legacy_id, created_at, updated_at
`

type CreateTransactionParams struct {
	TenantID         uuid.UUID           `json:"tenant_id"`
	Kind             string              `json:"kind"`
	PaymentMethodID  uuid.UUID           `json:"payment_method_id"`
	TotalAmount      decimal.Decimal     `json:"total_amount"`
	ActualPaidAmount decimal.Decimal     `json:"actual_paid_amount"`
	MemberID         pgtype.UUID         `json:"member_id"`
	CustomerName     *string             `json:"customer_name"`
	StaffID          pgtype.UUID         `json:"staff_id"`
	CardID           pgtype.UUID         `json:"card_id"`
	DiscountAmount   decimal.NullDecimal `json:"discount_amount"`
	TransactionTime  pgtype.Timestamptz  `json:"transaction_time"`
	Summary          *string             `json:"summary"`
	Notes            *string             `json:"notes"`
}

// 统一入口：消费 / 办卡 / 清挂账 都走这里，kind 区分
// discount_amount 可空默认 0；transaction_time 可空默认 now()
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.TenantID,
		arg.Kind,
		arg.PaymentMethodID,
		arg.TotalAmount,
		arg.ActualPaidAmount,
		arg.MemberID,
		arg.CustomerName,
		arg.StaffID,
		arg.CardID,
		arg.DiscountAmount,
		arg.TransactionTime,
		arg.Summary,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Status,
		&i.MemberID,
		&i.CustomerName,
		&i.StaffID,
		&i.PaymentMethodID,
		&i.CardID,
		&i.TotalAmount,
		&i.ActualPaidAmount,
		&i.DiscountAmount,
		&i.TransactionTime,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidedByName,
		&i.VoidReason,
		&i.Summary,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, tenant_id, kind, status, member_id, customer_name, staff_id, payment_method_id, card_id, total_amount, actual_paid_amount, discount_amount, transaction_time, voided_at, voided_by_user_id, voided_by_name, void_reason, summary, notes, legacy_id, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Status,
		&i.MemberID,
		&i.CustomerName,
		&i.StaffID,
		&i.PaymentMethodID,
		&i.CardID,
		&i.TotalAmount,
		&i.ActualPaidAmount,
		&i.DiscountAmount,
		&i.TransactionTime,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidedByName,
		&i.VoidReason,
		&i.Summary,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
  t.id, t.tenant_id, t.kind, t.status, t.member_id, t.customer_name, t.staff_id, t.payment_method_id, t.card_id, t.total_amount, t.actual_paid_amount, t.discount_amount, t.transaction_time, t.voided_at, t.voided_by_user_id, t.voided_by_name, t.void_reason, t.summary, t.notes, t.legacy_id, t.created_at, t.updated_at,
  m.name  AS member_name,
  -- 卡展示名：自定义面值卡按实际面值展示并带折扣后缀（迁移把 isCustomCard 塌缩为
  -- final_price，与卡型标价不同即为自定义），老板在老系统看惯的「自定义面值卡(¥N) n折」不丢
  COALESCE(CASE WHEN c.final_price <> ct.price
             THEN '自定义面值卡(¥' || to_char(c.final_price, 'FM9999999990.00') || ')'
             ELSE ct.name END
        || CASE WHEN c.final_discount_rate < 1
             THEN ' ' || rtrim(rtrim(to_char(c.final_discount_rate * 10, 'FM90.9'), '0'), '.') || '折'
             ELSE '' END, '')::text AS card_type_name,
  COALESCE((SELECT SUM(quantity)::int FROM transaction_items WHERE transaction_id = t.id), 0)::int AS item_qty,
  -- 明细标价合计：迁移把加价单 total 抬平到实收，原应收只在明细单价里，前端靠它显示「加 ¥N」
  COALESCE((SELECT SUM(ti.price * ti.quantity) FROM transaction_items ti WHERE ti.transaction_id = t.id), 0)::numeric(10,2) AS items_total,
  -- 挂账登记交易（0 实收）关联的挂账金额：流水里显示「挂账 ¥N」而不是令人困惑的 ¥0
  COALESCE((SELECT mc.amount FROM member_credits mc WHERE mc.charged_tx_id = t.id LIMIT 1), 0)::numeric(10,2) AS credit_amount,
  -- summary 为空时（老系统迁入的交易普遍如此）前端回退显示明细聚合，服务项目列不再一片「—」
  (SELECT string_agg(ti.service_name_snapshot
            || CASE WHEN ti.quantity > 1 THEN '×' || ti.quantity ELSE '' END, '、')
   FROM transaction_items ti WHERE ti.transaction_id = t.id) AS items_summary
FROM transactions t
LEFT JOIN members m     ON m.id = t.member_id
LEFT JOIN cards c       ON c.id = t.card_id
LEFT JOIN card_types ct ON ct.id = c.card_type_id
WHERE ($3::timestamptz IS NULL OR t.transaction_time >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR t.transaction_time <  $4::timestamptz)
  AND ($5::text              IS NULL OR t.kind             =  $5::text)
  AND ($6::uuid         IS NULL OR t.member_id       =  $6::uuid)
  -- 搜索范围与老系统对齐并扩展：会员姓名 / 手机号 / 非会员姓名 / 项目摘要 /
  -- 明细服务名；纯数字输入再按金额精确匹配（应收或实收）
  AND ($7::text IS NULL
       OR m.name ILIKE '%' || $7::text || '%'
       OR m.phone ILIKE '%' || $7::text || '%'
       OR t.customer_name ILIKE '%' || $7::text || '%'
       OR t.summary ILIKE '%' || $7::text || '%'
       OR EXISTS (SELECT 1 FROM transaction_items ti2
                  WHERE ti2.transaction_id = t.id
                    AND ti2.service_name_snapshot ILIKE '%' || $7::text || '%')
       OR ($7::text ~ '^[0-9]+(\.[0-9]{1,2})?$'
           AND (t.total_amount = $7::numeric
                OR t.actual_paid_amount = $7::numeric)))
  AND (
    $8::text IS NOT NULL AND t.status = $8::text
    OR $8::text IS NULL AND ($9::bool IS TRUE OR t.status = 'completed')
  )
ORDER BY t.transaction_time DESC, t.id DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsParams struct {
	Limit         int32              `json:"limit"`
	Offset        int32              `json:"offset"`
	StartDate     pgtype.Timestamptz `json:"start_date"`
	EndDate       pgtype.Timestamptz `json:"end_date"`
	Kind          *string            `json:"kind"`
	MemberID      pgtype.UUID        `json:"member_id"`
	Search        *string            `json:"search"`
	Status        *string            `json:"status"`
	IncludeVoided *bool              `json:"include_voided"`
}

type ListTransactionsRow struct {
	Transaction  Transaction     `json:"transaction"`
	MemberName   *string         `json:"member_name"`
	CardTypeName string          `json:"card_type_name"`
	ItemQty      int32           `json:"item_qty"`
	ItemsTotal   decimal.Decimal `json:"items_total"`
	CreditAmount decimal.Decimal `json:"credit_amount"`
	ItemsSummary []byte          `json:"items_summary"`
}

// 列出交易，附带会员名 / 卡类型名 / 项目数 (POS 收银底部 / 流水页展示)
//
//	status:         可选精确过滤（'completed' / 'voided'）
//	include_voided: 兼容参数，true 时等同不限 status；否则仅 completed（当 status 未指定时生效）
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
		arg.Kind,
		arg.MemberID,
		arg.Search,
		arg.Status,
		arg.IncludeVoided,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.TenantID,
			&i.Transaction.Kind,
			&i.Transaction.Status,
			&i.Transaction.MemberID,
			&i.Transaction.CustomerName,
			&i.Transaction.StaffID,
			&i.Transaction.PaymentMethodID,
			&i.Transaction.CardID,
			&i.Transaction.TotalAmount,
			&i.Transaction.ActualPaidAmount,
			&i.Transaction.DiscountAmount,
			&i.Transaction.TransactionTime,
			&i.Transaction.VoidedAt,
			&i.Transaction.VoidedByUserID,
			&i.Transaction.VoidedByName,
			&i.Transaction.VoidReason,
			&i.Transaction.Summary,
			&i.Transaction.Notes,
			&i.Transaction.LegacyID,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.MemberName,
			&i.CardTypeName,
			&i.ItemQty,
			&i.ItemsTotal,
			&i.CreditAmount,
			&i.ItemsSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTransactionForUpdate = `-- name: LockTransactionForUpdate :one
SELECT id, tenant_id, kind, status, member_id, customer_name, staff_id, payment_method_id, card_id, total_amount, actual_paid_amount, discount_amount, transaction_time, voided_at, voided_by_user_id, voided_by_name, void_reason, summary, notes, legacy_id, created_at, updated_at FROM transactions WHERE id = $1 FOR UPDATE
`

// 撤单路径：防止双击重复反向扣款
func (q *Queries) LockTransactionForUpdate(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, lockTransactionForUpdate, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Status,
		&i.MemberID,
		&i.CustomerName,
		&i.StaffID,
		&i.PaymentMethodID,
		&i.CardID,
		&i.TotalAmount,
		&i.ActualPaidAmount,
		&i.DiscountAmount,
		&i.TransactionTime,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidedByName,
		&i.VoidReason,
		&i.Summary,
		&i.Notes,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lookupTransactionsByIDs = `-- name: LookupTransactionsByIDs :many
SELECT t.id,
       t.total_amount,
       COALESCE(m.name, t.customer_name, '非会员')::text AS display_name
FROM transactions t
LEFT JOIN members m ON m.id = t.member_id
WHERE t.id = ANY($1::uuid[])
`

type LookupTransactionsByIDsRow struct {
	ID          uuid.UUID       `json:"id"`
	TotalAmount decimal.Decimal `json:"total_amount"`
	DisplayName string          `json:"display_name"`
}

// 批量返回 id + 简要信息（给操作日志对象列显示用）
func (q *Queries) LookupTransactionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]LookupTransactionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, lookupTransactionsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupTransactionsByIDsRow
	for rows.Next() {
		var i LookupTransactionsByIDsRow
		if err := rows.Scan(&i.ID, &i.TotalAmount, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTransactionsUpdatedAt = `-- name: MaxTransactionsUpdatedAt :one
SELECT COALESCE(MAX(updated_at), '1970-01-01 00:00:00+00'::timestamptz)::timestamptz AS max_updated_at
FROM transactions
WHERE ($1::timestamptz IS NULL OR transaction_time >= $1::timestamptz)
  AND ($2::timestamptz   IS NULL OR transaction_time <  $2::timestamptz)
  AND ($3::text              IS NULL OR kind              =  $3::text)
  AND ($4::uuid         IS NULL OR member_id        =  $4::uuid)
  AND ($5::text IS NULL
       OR EXISTS (SELECT 1 FROM members mm WHERE mm.id = transactions.member_id
                  AND (mm.name ILIKE '%' || $5::text || '%'
                       OR mm.phone ILIKE '%' || $5::text || '%'))
       OR customer_name ILIKE '%' || $5::text || '%'
       OR summary ILIKE '%' || $5::text || '%'
       OR EXISTS (SELECT 1 FROM transaction_items ti2
                  WHERE ti2.transaction_id = transactions.id
                    AND ti2.service_name_snapshot ILIKE '%' || $5::text || '%')
       OR ($5::text ~ '^[0-9]+(\.[0-9]{1,2})?$'
           AND (total_amount = $5::numeric
                OR actual_paid_amount = $5::numeric)))
  AND (
    $6::text IS NOT NULL AND status = $6::text
    OR $6::text IS NULL AND ($7::bool IS TRUE OR status = 'completed')
  )
`

type MaxTransactionsUpdatedAtParams struct {
	StartDate     pgtype.Timestamptz `json:"start_date"`
	EndDate       pgtype.Timestamptz `json:"end_date"`
	Kind          *string            `json:"kind"`
	MemberID      pgtype.UUID        `json:"member_id"`
	Search        *string            `json:"search"`
	Status        *string            `json:"status"`
	IncludeVoided *bool              `json:"include_voided"`
}

// 给 ETag 用：返回当前 filter 范围内最近一次写入的时间
// 同 ListTransactions 的 filter 子句保持一致，否则 ETag 会跨 filter 错误命中
func (q *Queries) MaxTransactionsUpdatedAt(ctx context.Context, arg MaxTransactionsUpdatedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, maxTransactionsUpdatedAt,
		arg.StartDate,
		arg.EndDate,
		arg.Kind,
		arg.MemberID,
		arg.Search,
		arg.Status,
		arg.IncludeVoided,
	)
	var max_updated_at pgtype.Timestamptz
	err := row.Scan(&max_updated_at)
	return max_updated_at, err
}

const voidTransaction = `-- name: VoidTransaction :exec
UPDATE transactions
SET status            = 'voided',
    voided_at         = now(),
    voided_by_user_id = $2,
    voided_by_name    = $3,
    void_reason       = $4::text,
    updated_at        = now()
WHERE id = $1 AND status = 'completed'
`

type VoidTransactionParams struct {
	ID             uuid.UUID   `json:"id"`
	VoidedByUserID pgtype.UUID `json:"voided_by_user_id"`
	VoidedByName   *string     `json:"voided_by_name"`
	Reason         *string     `json:"reason"`
}

// 软撤单（A4 实现完整逻辑；此 query 仅负责更新状态 + 审计字段）
func (q *Queries) VoidTransaction(ctx context.Context, arg VoidTransactionParams) error {
	_, err := q.db.Exec(ctx, voidTransaction,
		arg.ID,
		arg.VoidedByUserID,
		arg.VoidedByName,
		arg.Reason,
	)
	return err
}
